import { downloadXlsx } from "@/components/timetracking/reportExport";
import { formatInr } from "@/components/billing/utils";

type AnalyticsPayload = NonNullable<Awaited<ReturnType<typeof import("@/lib/analytics.functions").getFirmAnalytics>>>;

export function exportAnalyticsExcel(data: AnalyticsPayload, rangeLabel: string) {
  downloadXlsx(`firm-analytics-${rangeLabel.replace(/\s+/g, "-")}.xlsx`, [
    {
      name: "Revenue KPIs",
      rows: [
        { Metric: "Total Revenue", Value: data.revenue.totalRevenue },
        { Metric: "Collected", Value: data.revenue.revenueCollected },
        { Metric: "Outstanding", Value: data.revenue.outstandingDues },
        { Metric: "Change %", Value: data.revenue.revenueChangePct ?? "" },
      ],
    },
    {
      name: "Client Profitability",
      rows: data.clientProfitability.rows.map((r) => ({
        Client: r.clientName,
        Invoiced: r.totalInvoiced,
        Paid: r.totalPaid,
        Outstanding: r.outstanding,
        Hours: r.hoursSpent,
        "Rev/Hour": r.revenuePerHour,
        Services: r.servicesUsed.join(", "),
      })),
    },
    {
      name: "Staff Performance",
      rows: data.staff.rows.map((r) => ({
        Staff: r.name,
        Designation: r.designation,
        Hours: r.hours,
        "Billable Hrs": r.billableHours,
        "Billable %": r.billablePct,
        "Tasks Done": r.tasksCompleted,
        Overdue: r.tasksOverdue,
        Revenue: r.revenueGenerated,
      })),
    },
    {
      name: "Compliance",
      rows: data.compliance.byCategory.map((r) => ({
        Category: r.category,
        Completed: r.completed,
        "On Time": r.onTime,
        Late: r.late,
        Pending: r.pending,
        "On-Time Rate %": r.onTimeRate,
      })),
    },
    {
      name: "Risk Radar",
      rows: data.portfolio.riskRadar.map((r) => ({
        Client: r.clientName,
        "Overdue Filings": r.overdueFilings,
        "Open Notices": r.openNotices,
        Outstanding: r.outstandingInvoice,
        "Overdue Tasks": r.overdueTasks,
        "Risk Score": r.riskScore,
      })),
    },
    {
      name: "Outstanding Invoices",
      rows: data.billing.topOutstanding.map((r) => ({
        Client: r.clientName,
        Invoice: r.invoiceNumber,
        Date: r.invoiceDate,
        Amount: r.amount,
        "Days Outstanding": r.daysOutstanding,
      })),
    },
  ]);
}

export function printAnalyticsReport(data: AnalyticsPayload, rangeLabel: string) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Firm Analytics — ${rangeLabel}</title>
<style>
  body { font-family: system-ui, sans-serif; padding: 32px; color: #111; font-size: 12px; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  h2 { font-size: 14px; margin: 24px 0 8px; border-bottom: 2px solid #1f6f4a; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
  th { background: #f4f4f5; }
  .kpis { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
  .kpi { border: 1px solid #ddd; padding: 12px; border-radius: 8px; }
  .kpi label { font-size: 10px; color: #666; text-transform: uppercase; }
  .kpi val { display: block; font-size: 16px; font-weight: 600; margin-top: 4px; }
  @media print { body { padding: 16px; } }
</style></head><body>
<h1>GSTify Firm Analytics</h1>
<p>Period: ${rangeLabel} (${data.range.from} to ${data.range.to})</p>
<div class="kpis">
  <div class="kpi"><label>Total Revenue</label><val>${formatInr(data.revenue.totalRevenue)}</val></div>
  <div class="kpi"><label>Collected</label><val>${formatInr(data.revenue.revenueCollected)}</val></div>
  <div class="kpi"><label>Outstanding</label><val>${formatInr(data.revenue.outstandingDues)}</val></div>
  <div class="kpi"><label>Billable %</label><val>${data.staff.kpis.billablePct}%</val></div>
</div>
<h2>Top Clients by Revenue</h2>
<table><tr><th>Client</th><th>Invoiced</th><th>Paid</th><th>Rev/Hr</th></tr>
${data.clientProfitability.rows.slice(0, 15).map((r) =>
  `<tr><td>${r.clientName}</td><td>${formatInr(r.totalInvoiced)}</td><td>${formatInr(r.totalPaid)}</td><td>${formatInr(r.revenuePerHour)}</td></tr>`,
).join("")}
</table>
<h2>Staff Performance</h2>
<table><tr><th>Staff</th><th>Hours</th><th>Billable %</th><th>Revenue</th></tr>
${data.staff.rows.map((r) =>
  `<tr><td>${r.name}</td><td>${r.hours}</td><td>${r.billablePct}%</td><td>${formatInr(r.revenueGenerated)}</td></tr>`,
).join("")}
</table>
<h2>Compliance by Category</h2>
<table><tr><th>Category</th><th>On-Time Rate</th><th>Pending</th></tr>
${data.compliance.byCategory.map((r) =>
  `<tr><td>${r.category}</td><td>${r.onTimeRate}%</td><td>${r.pending}</td></tr>`,
).join("")}
</table>
<p style="margin-top:32px;color:#666;font-size:10px">Generated by GSTify · ${new Date().toLocaleString("en-IN")}</p>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.onload = () => w.print();
}
