/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupCaRouteImport } from './routes/signup.ca'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedCaRouteImport } from './routes/_authenticated/ca'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedCaIndexRouteImport } from './routes/_authenticated/ca.index'
import { Route as AuthenticatedClientUploadRouteImport } from './routes/_authenticated/client.upload'
import { Route as AuthenticatedClientRequestsRouteImport } from './routes/_authenticated/client.requests'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/client.documents'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/client.dashboard'
import { Route as AuthenticatedClientAgreementsRouteImport } from './routes/_authenticated/client.agreements'
import { Route as AuthenticatedCaVaultRouteImport } from './routes/_authenticated/ca.vault'
import { Route as AuthenticatedCaTimesheetsRouteImport } from './routes/_authenticated/ca.timesheets'
import { Route as AuthenticatedCaTasksRouteImport } from './routes/_authenticated/ca.tasks'
import { Route as AuthenticatedCaStaffRouteImport } from './routes/_authenticated/ca.staff'
import { Route as AuthenticatedCaSettingsRouteImport } from './routes/_authenticated/ca.settings'
import { Route as AuthenticatedCaReportsRouteImport } from './routes/_authenticated/ca.reports'
import { Route as AuthenticatedCaHelpRouteImport } from './routes/_authenticated/ca.help'
import { Route as AuthenticatedCaGstLibraryRouteImport } from './routes/_authenticated/ca.gst-library'
import { Route as AuthenticatedCaGrowRouteImport } from './routes/_authenticated/ca.grow'
import { Route as AuthenticatedCaEInvoicesRouteImport } from './routes/_authenticated/ca.e-invoices'
import { Route as AuthenticatedCaDscVaultRouteImport } from './routes/_authenticated/ca.dsc-vault'
import { Route as AuthenticatedCaDashboardRouteImport } from './routes/_authenticated/ca.dashboard'
import { Route as AuthenticatedCaComplianceCalendarRouteImport } from './routes/_authenticated/ca.compliance-calendar'
import { Route as AuthenticatedCaCommunicationsRouteImport } from './routes/_authenticated/ca.communications'
import { Route as AuthenticatedCaClientsRouteImport } from './routes/_authenticated/ca.clients'
import { Route as AuthenticatedCaBillingRouteImport } from './routes/_authenticated/ca.billing'
import { Route as AuthenticatedCaAnalyticsRouteImport } from './routes/_authenticated/ca.analytics'
import { Route as AuthenticatedCaAgreementsRouteImport } from './routes/_authenticated/ca.agreements'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin.referrals'
import { Route as AuthenticatedClientDashboardIndexRouteImport } from './routes/_authenticated/client.dashboard.index'
import { Route as AuthenticatedClientDashboardTasksRouteImport } from './routes/_authenticated/client.dashboard.tasks'
import { Route as AuthenticatedClientDashboardQueriesRouteImport } from './routes/_authenticated/client.dashboard.queries'
import { Route as AuthenticatedClientDashboardProfileRouteImport } from './routes/_authenticated/client.dashboard.profile'
import { Route as AuthenticatedClientDashboardInvoicesRouteImport } from './routes/_authenticated/client.dashboard.invoices'
import { Route as AuthenticatedClientDashboardHomeRouteImport } from './routes/_authenticated/client.dashboard.home'
import { Route as AuthenticatedClientDashboardFilingsRouteImport } from './routes/_authenticated/client.dashboard.filings'
import { Route as AuthenticatedClientDashboardComplianceRouteImport } from './routes/_authenticated/client.dashboard.compliance'
import { Route as AuthenticatedCaTimesheetsMyTimesheetRouteImport } from './routes/_authenticated/ca.timesheets.my-timesheet'
import { Route as AuthenticatedCaTasksMyTasksRouteImport } from './routes/_authenticated/ca.tasks.my-tasks'
import { Route as AuthenticatedCaStaffUserIdRouteImport } from './routes/_authenticated/ca.staff.$userId'
import { Route as AuthenticatedCaSettingsTallyMappingsRouteImport } from './routes/_authenticated/ca.settings.tally-mappings'
import { Route as AuthenticatedCaSettingsReferralRouteImport } from './routes/_authenticated/ca.settings.referral'
import { Route as AuthenticatedCaSettingsEInvoiceRouteImport } from './routes/_authenticated/ca.settings.e-invoice'
import { Route as AuthenticatedCaSettingsBillingSubscriptionRouteImport } from './routes/_authenticated/ca.settings.billing-subscription'
import { Route as AuthenticatedCaSettingsBillingRouteImport } from './routes/_authenticated/ca.settings.billing'
import { Route as AuthenticatedCaSettingsAgreementTemplatesRouteImport } from './routes/_authenticated/ca.settings.agreement-templates'
import { Route as AuthenticatedCaReportsTimesheetsRouteImport } from './routes/_authenticated/ca.reports.timesheets'
import { Route as AuthenticatedCaMyProfileCpeRouteImport } from './routes/_authenticated/ca.my-profile.cpe'
import { Route as AuthenticatedCaClientsClientIdRouteImport } from './routes/_authenticated/ca.clients.$clientId'
import { Route as AuthenticatedCaBillingServicesRouteImport } from './routes/_authenticated/ca.billing.services'
import { Route as AuthenticatedCaBillingReportsRouteImport } from './routes/_authenticated/ca.billing.reports'
import { Route as AuthenticatedCaBillingNewRouteImport } from './routes/_authenticated/ca.billing.new'
import { Route as AuthenticatedCaBillingInvoiceIdRouteImport } from './routes/_authenticated/ca.billing.$invoiceId'
import { Route as AuthenticatedCaAgreementsNewRouteImport } from './routes/_authenticated/ca.agreements.new'
import { Route as AuthenticatedCaAgreementsAgreementIdRouteImport } from './routes/_authenticated/ca.agreements.$agreementId'
import { Route as AuthenticatedCaClientsClientIdTallyImportRouteImport } from './routes/_authenticated/ca.clients.$clientId.tally-import'
import { Route as AuthenticatedCaClientsClientIdTallyExportRouteImport } from './routes/_authenticated/ca.clients.$clientId.tally-export'
import { Route as AuthenticatedCaClientsClientIdEInvoicesRouteImport } from './routes/_authenticated/ca.clients.$clientId.e-invoices'
import { Route as AuthenticatedCaClientsClientIdDocumentsRouteImport } from './routes/_authenticated/ca.clients.$clientId.documents'
import { Route as AuthenticatedCaClientsClientIdComplianceRouteImport } from './routes/_authenticated/ca.clients.$clientId.compliance'
import { Route as AuthenticatedCaBillingInvoiceIdEditRouteImport } from './routes/_authenticated/ca.billing.$invoiceId.edit'
import { Route as AuthenticatedCaAgreementsAgreementIdEditRouteImport } from './routes/_authenticated/ca.agreements.$agreementId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCaRoute = SignupCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => SignupRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaRoute = AuthenticatedCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedCaIndexRoute = AuthenticatedCaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedClientUploadRoute =
  AuthenticatedClientUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientRequestsRoute =
  AuthenticatedClientRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientAgreementsRoute =
  AuthenticatedClientAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedCaVaultRoute = AuthenticatedCaVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaTimesheetsRoute =
  AuthenticatedCaTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaTasksRoute = AuthenticatedCaTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaStaffRoute = AuthenticatedCaStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaSettingsRoute = AuthenticatedCaSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaReportsRoute = AuthenticatedCaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaHelpRoute = AuthenticatedCaHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaGstLibraryRoute =
  AuthenticatedCaGstLibraryRouteImport.update({
    id: '/gst-library',
    path: '/gst-library',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaGrowRoute = AuthenticatedCaGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaEInvoicesRoute =
  AuthenticatedCaEInvoicesRouteImport.update({
    id: '/e-invoices',
    path: '/e-invoices',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaDscVaultRoute = AuthenticatedCaDscVaultRouteImport.update({
  id: '/dsc-vault',
  path: '/dsc-vault',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaDashboardRoute =
  AuthenticatedCaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaComplianceCalendarRoute =
  AuthenticatedCaComplianceCalendarRouteImport.update({
    id: '/compliance-calendar',
    path: '/compliance-calendar',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaCommunicationsRoute =
  AuthenticatedCaCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaClientsRoute = AuthenticatedCaClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaBillingRoute = AuthenticatedCaBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaAnalyticsRoute =
  AuthenticatedCaAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaAgreementsRoute =
  AuthenticatedCaAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/admin/referrals',
    path: '/admin/referrals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientDashboardIndexRoute =
  AuthenticatedClientDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardTasksRoute =
  AuthenticatedClientDashboardTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardQueriesRoute =
  AuthenticatedClientDashboardQueriesRouteImport.update({
    id: '/queries',
    path: '/queries',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardProfileRoute =
  AuthenticatedClientDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardInvoicesRoute =
  AuthenticatedClientDashboardInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardHomeRoute =
  AuthenticatedClientDashboardHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardFilingsRoute =
  AuthenticatedClientDashboardFilingsRouteImport.update({
    id: '/filings',
    path: '/filings',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedClientDashboardComplianceRoute =
  AuthenticatedClientDashboardComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedClientDashboardRoute,
  } as any)
const AuthenticatedCaTimesheetsMyTimesheetRoute =
  AuthenticatedCaTimesheetsMyTimesheetRouteImport.update({
    id: '/my-timesheet',
    path: '/my-timesheet',
    getParentRoute: () => AuthenticatedCaTimesheetsRoute,
  } as any)
const AuthenticatedCaTasksMyTasksRoute =
  AuthenticatedCaTasksMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedCaTasksRoute,
  } as any)
const AuthenticatedCaStaffUserIdRoute =
  AuthenticatedCaStaffUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedCaStaffRoute,
  } as any)
const AuthenticatedCaSettingsTallyMappingsRoute =
  AuthenticatedCaSettingsTallyMappingsRouteImport.update({
    id: '/tally-mappings',
    path: '/tally-mappings',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaSettingsReferralRoute =
  AuthenticatedCaSettingsReferralRouteImport.update({
    id: '/referral',
    path: '/referral',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaSettingsEInvoiceRoute =
  AuthenticatedCaSettingsEInvoiceRouteImport.update({
    id: '/e-invoice',
    path: '/e-invoice',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaSettingsBillingSubscriptionRoute =
  AuthenticatedCaSettingsBillingSubscriptionRouteImport.update({
    id: '/billing-subscription',
    path: '/billing-subscription',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaSettingsBillingRoute =
  AuthenticatedCaSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaSettingsAgreementTemplatesRoute =
  AuthenticatedCaSettingsAgreementTemplatesRouteImport.update({
    id: '/agreement-templates',
    path: '/agreement-templates',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaReportsTimesheetsRoute =
  AuthenticatedCaReportsTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => AuthenticatedCaReportsRoute,
  } as any)
const AuthenticatedCaMyProfileCpeRoute =
  AuthenticatedCaMyProfileCpeRouteImport.update({
    id: '/my-profile/cpe',
    path: '/my-profile/cpe',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaClientsClientIdRoute =
  AuthenticatedCaClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedCaClientsRoute,
  } as any)
const AuthenticatedCaBillingServicesRoute =
  AuthenticatedCaBillingServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaBillingReportsRoute =
  AuthenticatedCaBillingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaBillingNewRoute =
  AuthenticatedCaBillingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaBillingInvoiceIdRoute =
  AuthenticatedCaBillingInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaAgreementsNewRoute =
  AuthenticatedCaAgreementsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCaAgreementsRoute,
  } as any)
const AuthenticatedCaAgreementsAgreementIdRoute =
  AuthenticatedCaAgreementsAgreementIdRouteImport.update({
    id: '/$agreementId',
    path: '/$agreementId',
    getParentRoute: () => AuthenticatedCaAgreementsRoute,
  } as any)
const AuthenticatedCaClientsClientIdTallyImportRoute =
  AuthenticatedCaClientsClientIdTallyImportRouteImport.update({
    id: '/tally-import',
    path: '/tally-import',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaClientsClientIdTallyExportRoute =
  AuthenticatedCaClientsClientIdTallyExportRouteImport.update({
    id: '/tally-export',
    path: '/tally-export',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaClientsClientIdEInvoicesRoute =
  AuthenticatedCaClientsClientIdEInvoicesRouteImport.update({
    id: '/e-invoices',
    path: '/e-invoices',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaClientsClientIdDocumentsRoute =
  AuthenticatedCaClientsClientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaClientsClientIdComplianceRoute =
  AuthenticatedCaClientsClientIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaBillingInvoiceIdEditRoute =
  AuthenticatedCaBillingInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedCaBillingInvoiceIdRoute,
  } as any)
const AuthenticatedCaAgreementsAgreementIdEditRoute =
  AuthenticatedCaAgreementsAgreementIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedCaAgreementsAgreementIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/ca': typeof AuthenticatedCaRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup/': typeof SignupIndexRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/ca/agreements': typeof AuthenticatedCaAgreementsRouteWithChildren
  '/ca/analytics': typeof AuthenticatedCaAnalyticsRoute
  '/ca/billing': typeof AuthenticatedCaBillingRouteWithChildren
  '/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/ca/communications': typeof AuthenticatedCaCommunicationsRoute
  '/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/ca/dsc-vault': typeof AuthenticatedCaDscVaultRoute
  '/ca/e-invoices': typeof AuthenticatedCaEInvoicesRoute
  '/ca/grow': typeof AuthenticatedCaGrowRoute
  '/ca/gst-library': typeof AuthenticatedCaGstLibraryRoute
  '/ca/help': typeof AuthenticatedCaHelpRoute
  '/ca/reports': typeof AuthenticatedCaReportsRouteWithChildren
  '/ca/settings': typeof AuthenticatedCaSettingsRouteWithChildren
  '/ca/staff': typeof AuthenticatedCaStaffRouteWithChildren
  '/ca/tasks': typeof AuthenticatedCaTasksRouteWithChildren
  '/ca/timesheets': typeof AuthenticatedCaTimesheetsRouteWithChildren
  '/ca/vault': typeof AuthenticatedCaVaultRoute
  '/client/agreements': typeof AuthenticatedClientAgreementsRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRouteWithChildren
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/requests': typeof AuthenticatedClientRequestsRoute
  '/client/upload': typeof AuthenticatedClientUploadRoute
  '/ca/': typeof AuthenticatedCaIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/ca/agreements/$agreementId': typeof AuthenticatedCaAgreementsAgreementIdRouteWithChildren
  '/ca/agreements/new': typeof AuthenticatedCaAgreementsNewRoute
  '/ca/billing/$invoiceId': typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  '/ca/billing/new': typeof AuthenticatedCaBillingNewRoute
  '/ca/billing/reports': typeof AuthenticatedCaBillingReportsRoute
  '/ca/billing/services': typeof AuthenticatedCaBillingServicesRoute
  '/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/ca/my-profile/cpe': typeof AuthenticatedCaMyProfileCpeRoute
  '/ca/reports/timesheets': typeof AuthenticatedCaReportsTimesheetsRoute
  '/ca/settings/agreement-templates': typeof AuthenticatedCaSettingsAgreementTemplatesRoute
  '/ca/settings/billing': typeof AuthenticatedCaSettingsBillingRoute
  '/ca/settings/billing-subscription': typeof AuthenticatedCaSettingsBillingSubscriptionRoute
  '/ca/settings/e-invoice': typeof AuthenticatedCaSettingsEInvoiceRoute
  '/ca/settings/referral': typeof AuthenticatedCaSettingsReferralRoute
  '/ca/settings/tally-mappings': typeof AuthenticatedCaSettingsTallyMappingsRoute
  '/ca/staff/$userId': typeof AuthenticatedCaStaffUserIdRoute
  '/ca/tasks/my-tasks': typeof AuthenticatedCaTasksMyTasksRoute
  '/ca/timesheets/my-timesheet': typeof AuthenticatedCaTimesheetsMyTimesheetRoute
  '/client/dashboard/compliance': typeof AuthenticatedClientDashboardComplianceRoute
  '/client/dashboard/filings': typeof AuthenticatedClientDashboardFilingsRoute
  '/client/dashboard/home': typeof AuthenticatedClientDashboardHomeRoute
  '/client/dashboard/invoices': typeof AuthenticatedClientDashboardInvoicesRoute
  '/client/dashboard/profile': typeof AuthenticatedClientDashboardProfileRoute
  '/client/dashboard/queries': typeof AuthenticatedClientDashboardQueriesRoute
  '/client/dashboard/tasks': typeof AuthenticatedClientDashboardTasksRoute
  '/client/dashboard/': typeof AuthenticatedClientDashboardIndexRoute
  '/ca/agreements/$agreementId/edit': typeof AuthenticatedCaAgreementsAgreementIdEditRoute
  '/ca/billing/$invoiceId/edit': typeof AuthenticatedCaBillingInvoiceIdEditRoute
  '/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
  '/ca/clients/$clientId/documents': typeof AuthenticatedCaClientsClientIdDocumentsRoute
  '/ca/clients/$clientId/e-invoices': typeof AuthenticatedCaClientsClientIdEInvoicesRoute
  '/ca/clients/$clientId/tally-export': typeof AuthenticatedCaClientsClientIdTallyExportRoute
  '/ca/clients/$clientId/tally-import': typeof AuthenticatedCaClientsClientIdTallyImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup': typeof SignupIndexRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/ca/agreements': typeof AuthenticatedCaAgreementsRouteWithChildren
  '/ca/analytics': typeof AuthenticatedCaAnalyticsRoute
  '/ca/billing': typeof AuthenticatedCaBillingRouteWithChildren
  '/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/ca/communications': typeof AuthenticatedCaCommunicationsRoute
  '/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/ca/dsc-vault': typeof AuthenticatedCaDscVaultRoute
  '/ca/e-invoices': typeof AuthenticatedCaEInvoicesRoute
  '/ca/grow': typeof AuthenticatedCaGrowRoute
  '/ca/gst-library': typeof AuthenticatedCaGstLibraryRoute
  '/ca/help': typeof AuthenticatedCaHelpRoute
  '/ca/reports': typeof AuthenticatedCaReportsRouteWithChildren
  '/ca/settings': typeof AuthenticatedCaSettingsRouteWithChildren
  '/ca/staff': typeof AuthenticatedCaStaffRouteWithChildren
  '/ca/tasks': typeof AuthenticatedCaTasksRouteWithChildren
  '/ca/timesheets': typeof AuthenticatedCaTimesheetsRouteWithChildren
  '/ca/vault': typeof AuthenticatedCaVaultRoute
  '/client/agreements': typeof AuthenticatedClientAgreementsRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/requests': typeof AuthenticatedClientRequestsRoute
  '/client/upload': typeof AuthenticatedClientUploadRoute
  '/ca': typeof AuthenticatedCaIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/ca/agreements/$agreementId': typeof AuthenticatedCaAgreementsAgreementIdRouteWithChildren
  '/ca/agreements/new': typeof AuthenticatedCaAgreementsNewRoute
  '/ca/billing/$invoiceId': typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  '/ca/billing/new': typeof AuthenticatedCaBillingNewRoute
  '/ca/billing/reports': typeof AuthenticatedCaBillingReportsRoute
  '/ca/billing/services': typeof AuthenticatedCaBillingServicesRoute
  '/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/ca/my-profile/cpe': typeof AuthenticatedCaMyProfileCpeRoute
  '/ca/reports/timesheets': typeof AuthenticatedCaReportsTimesheetsRoute
  '/ca/settings/agreement-templates': typeof AuthenticatedCaSettingsAgreementTemplatesRoute
  '/ca/settings/billing': typeof AuthenticatedCaSettingsBillingRoute
  '/ca/settings/billing-subscription': typeof AuthenticatedCaSettingsBillingSubscriptionRoute
  '/ca/settings/e-invoice': typeof AuthenticatedCaSettingsEInvoiceRoute
  '/ca/settings/referral': typeof AuthenticatedCaSettingsReferralRoute
  '/ca/settings/tally-mappings': typeof AuthenticatedCaSettingsTallyMappingsRoute
  '/ca/staff/$userId': typeof AuthenticatedCaStaffUserIdRoute
  '/ca/tasks/my-tasks': typeof AuthenticatedCaTasksMyTasksRoute
  '/ca/timesheets/my-timesheet': typeof AuthenticatedCaTimesheetsMyTimesheetRoute
  '/client/dashboard/compliance': typeof AuthenticatedClientDashboardComplianceRoute
  '/client/dashboard/filings': typeof AuthenticatedClientDashboardFilingsRoute
  '/client/dashboard/home': typeof AuthenticatedClientDashboardHomeRoute
  '/client/dashboard/invoices': typeof AuthenticatedClientDashboardInvoicesRoute
  '/client/dashboard/profile': typeof AuthenticatedClientDashboardProfileRoute
  '/client/dashboard/queries': typeof AuthenticatedClientDashboardQueriesRoute
  '/client/dashboard/tasks': typeof AuthenticatedClientDashboardTasksRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardIndexRoute
  '/ca/agreements/$agreementId/edit': typeof AuthenticatedCaAgreementsAgreementIdEditRoute
  '/ca/billing/$invoiceId/edit': typeof AuthenticatedCaBillingInvoiceIdEditRoute
  '/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
  '/ca/clients/$clientId/documents': typeof AuthenticatedCaClientsClientIdDocumentsRoute
  '/ca/clients/$clientId/e-invoices': typeof AuthenticatedCaClientsClientIdEInvoicesRoute
  '/ca/clients/$clientId/tally-export': typeof AuthenticatedCaClientsClientIdTallyExportRoute
  '/ca/clients/$clientId/tally-import': typeof AuthenticatedCaClientsClientIdTallyImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/ca': typeof AuthenticatedCaRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/ca/agreements': typeof AuthenticatedCaAgreementsRouteWithChildren
  '/_authenticated/ca/analytics': typeof AuthenticatedCaAnalyticsRoute
  '/_authenticated/ca/billing': typeof AuthenticatedCaBillingRouteWithChildren
  '/_authenticated/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/_authenticated/ca/communications': typeof AuthenticatedCaCommunicationsRoute
  '/_authenticated/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/_authenticated/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/_authenticated/ca/dsc-vault': typeof AuthenticatedCaDscVaultRoute
  '/_authenticated/ca/e-invoices': typeof AuthenticatedCaEInvoicesRoute
  '/_authenticated/ca/grow': typeof AuthenticatedCaGrowRoute
  '/_authenticated/ca/gst-library': typeof AuthenticatedCaGstLibraryRoute
  '/_authenticated/ca/help': typeof AuthenticatedCaHelpRoute
  '/_authenticated/ca/reports': typeof AuthenticatedCaReportsRouteWithChildren
  '/_authenticated/ca/settings': typeof AuthenticatedCaSettingsRouteWithChildren
  '/_authenticated/ca/staff': typeof AuthenticatedCaStaffRouteWithChildren
  '/_authenticated/ca/tasks': typeof AuthenticatedCaTasksRouteWithChildren
  '/_authenticated/ca/timesheets': typeof AuthenticatedCaTimesheetsRouteWithChildren
  '/_authenticated/ca/vault': typeof AuthenticatedCaVaultRoute
  '/_authenticated/client/agreements': typeof AuthenticatedClientAgreementsRoute
  '/_authenticated/client/dashboard': typeof AuthenticatedClientDashboardRouteWithChildren
  '/_authenticated/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/client/requests': typeof AuthenticatedClientRequestsRoute
  '/_authenticated/client/upload': typeof AuthenticatedClientUploadRoute
  '/_authenticated/ca/': typeof AuthenticatedCaIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/ca/agreements/$agreementId': typeof AuthenticatedCaAgreementsAgreementIdRouteWithChildren
  '/_authenticated/ca/agreements/new': typeof AuthenticatedCaAgreementsNewRoute
  '/_authenticated/ca/billing/$invoiceId': typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  '/_authenticated/ca/billing/new': typeof AuthenticatedCaBillingNewRoute
  '/_authenticated/ca/billing/reports': typeof AuthenticatedCaBillingReportsRoute
  '/_authenticated/ca/billing/services': typeof AuthenticatedCaBillingServicesRoute
  '/_authenticated/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/_authenticated/ca/my-profile/cpe': typeof AuthenticatedCaMyProfileCpeRoute
  '/_authenticated/ca/reports/timesheets': typeof AuthenticatedCaReportsTimesheetsRoute
  '/_authenticated/ca/settings/agreement-templates': typeof AuthenticatedCaSettingsAgreementTemplatesRoute
  '/_authenticated/ca/settings/billing': typeof AuthenticatedCaSettingsBillingRoute
  '/_authenticated/ca/settings/billing-subscription': typeof AuthenticatedCaSettingsBillingSubscriptionRoute
  '/_authenticated/ca/settings/e-invoice': typeof AuthenticatedCaSettingsEInvoiceRoute
  '/_authenticated/ca/settings/referral': typeof AuthenticatedCaSettingsReferralRoute
  '/_authenticated/ca/settings/tally-mappings': typeof AuthenticatedCaSettingsTallyMappingsRoute
  '/_authenticated/ca/staff/$userId': typeof AuthenticatedCaStaffUserIdRoute
  '/_authenticated/ca/tasks/my-tasks': typeof AuthenticatedCaTasksMyTasksRoute
  '/_authenticated/ca/timesheets/my-timesheet': typeof AuthenticatedCaTimesheetsMyTimesheetRoute
  '/_authenticated/client/dashboard/compliance': typeof AuthenticatedClientDashboardComplianceRoute
  '/_authenticated/client/dashboard/filings': typeof AuthenticatedClientDashboardFilingsRoute
  '/_authenticated/client/dashboard/home': typeof AuthenticatedClientDashboardHomeRoute
  '/_authenticated/client/dashboard/invoices': typeof AuthenticatedClientDashboardInvoicesRoute
  '/_authenticated/client/dashboard/profile': typeof AuthenticatedClientDashboardProfileRoute
  '/_authenticated/client/dashboard/queries': typeof AuthenticatedClientDashboardQueriesRoute
  '/_authenticated/client/dashboard/tasks': typeof AuthenticatedClientDashboardTasksRoute
  '/_authenticated/client/dashboard/': typeof AuthenticatedClientDashboardIndexRoute
  '/_authenticated/ca/agreements/$agreementId/edit': typeof AuthenticatedCaAgreementsAgreementIdEditRoute
  '/_authenticated/ca/billing/$invoiceId/edit': typeof AuthenticatedCaBillingInvoiceIdEditRoute
  '/_authenticated/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
  '/_authenticated/ca/clients/$clientId/documents': typeof AuthenticatedCaClientsClientIdDocumentsRoute
  '/_authenticated/ca/clients/$clientId/e-invoices': typeof AuthenticatedCaClientsClientIdEInvoicesRoute
  '/_authenticated/ca/clients/$clientId/tally-export': typeof AuthenticatedCaClientsClientIdTallyExportRoute
  '/_authenticated/ca/clients/$clientId/tally-import': typeof AuthenticatedCaClientsClientIdTallyImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/assistant'
    | '/ca'
    | '/client'
    | '/dashboard'
    | '/invoices'
    | '/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/sign/$token'
    | '/signup/ca'
    | '/signup/'
    | '/admin/referrals'
    | '/ca/agreements'
    | '/ca/analytics'
    | '/ca/billing'
    | '/ca/clients'
    | '/ca/communications'
    | '/ca/compliance-calendar'
    | '/ca/dashboard'
    | '/ca/dsc-vault'
    | '/ca/e-invoices'
    | '/ca/grow'
    | '/ca/gst-library'
    | '/ca/help'
    | '/ca/reports'
    | '/ca/settings'
    | '/ca/staff'
    | '/ca/tasks'
    | '/ca/timesheets'
    | '/ca/vault'
    | '/client/agreements'
    | '/client/dashboard'
    | '/client/documents'
    | '/client/requests'
    | '/client/upload'
    | '/ca/'
    | '/client/'
    | '/ca/agreements/$agreementId'
    | '/ca/agreements/new'
    | '/ca/billing/$invoiceId'
    | '/ca/billing/new'
    | '/ca/billing/reports'
    | '/ca/billing/services'
    | '/ca/clients/$clientId'
    | '/ca/my-profile/cpe'
    | '/ca/reports/timesheets'
    | '/ca/settings/agreement-templates'
    | '/ca/settings/billing'
    | '/ca/settings/billing-subscription'
    | '/ca/settings/e-invoice'
    | '/ca/settings/referral'
    | '/ca/settings/tally-mappings'
    | '/ca/staff/$userId'
    | '/ca/tasks/my-tasks'
    | '/ca/timesheets/my-timesheet'
    | '/client/dashboard/compliance'
    | '/client/dashboard/filings'
    | '/client/dashboard/home'
    | '/client/dashboard/invoices'
    | '/client/dashboard/profile'
    | '/client/dashboard/queries'
    | '/client/dashboard/tasks'
    | '/client/dashboard/'
    | '/ca/agreements/$agreementId/edit'
    | '/ca/billing/$invoiceId/edit'
    | '/ca/clients/$clientId/compliance'
    | '/ca/clients/$clientId/documents'
    | '/ca/clients/$clientId/e-invoices'
    | '/ca/clients/$clientId/tally-export'
    | '/ca/clients/$clientId/tally-import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/pricing'
    | '/assistant'
    | '/dashboard'
    | '/invoices'
    | '/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/sign/$token'
    | '/signup/ca'
    | '/signup'
    | '/admin/referrals'
    | '/ca/agreements'
    | '/ca/analytics'
    | '/ca/billing'
    | '/ca/clients'
    | '/ca/communications'
    | '/ca/compliance-calendar'
    | '/ca/dashboard'
    | '/ca/dsc-vault'
    | '/ca/e-invoices'
    | '/ca/grow'
    | '/ca/gst-library'
    | '/ca/help'
    | '/ca/reports'
    | '/ca/settings'
    | '/ca/staff'
    | '/ca/tasks'
    | '/ca/timesheets'
    | '/ca/vault'
    | '/client/agreements'
    | '/client/documents'
    | '/client/requests'
    | '/client/upload'
    | '/ca'
    | '/client'
    | '/ca/agreements/$agreementId'
    | '/ca/agreements/new'
    | '/ca/billing/$invoiceId'
    | '/ca/billing/new'
    | '/ca/billing/reports'
    | '/ca/billing/services'
    | '/ca/clients/$clientId'
    | '/ca/my-profile/cpe'
    | '/ca/reports/timesheets'
    | '/ca/settings/agreement-templates'
    | '/ca/settings/billing'
    | '/ca/settings/billing-subscription'
    | '/ca/settings/e-invoice'
    | '/ca/settings/referral'
    | '/ca/settings/tally-mappings'
    | '/ca/staff/$userId'
    | '/ca/tasks/my-tasks'
    | '/ca/timesheets/my-timesheet'
    | '/client/dashboard/compliance'
    | '/client/dashboard/filings'
    | '/client/dashboard/home'
    | '/client/dashboard/invoices'
    | '/client/dashboard/profile'
    | '/client/dashboard/queries'
    | '/client/dashboard/tasks'
    | '/client/dashboard'
    | '/ca/agreements/$agreementId/edit'
    | '/ca/billing/$invoiceId/edit'
    | '/ca/clients/$clientId/compliance'
    | '/ca/clients/$clientId/documents'
    | '/ca/clients/$clientId/e-invoices'
    | '/ca/clients/$clientId/tally-export'
    | '/ca/clients/$clientId/tally-import'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/join'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_authenticated/assistant'
    | '/_authenticated/ca'
    | '/_authenticated/client'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/sign/$token'
    | '/signup/ca'
    | '/signup/'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/ca/agreements'
    | '/_authenticated/ca/analytics'
    | '/_authenticated/ca/billing'
    | '/_authenticated/ca/clients'
    | '/_authenticated/ca/communications'
    | '/_authenticated/ca/compliance-calendar'
    | '/_authenticated/ca/dashboard'
    | '/_authenticated/ca/dsc-vault'
    | '/_authenticated/ca/e-invoices'
    | '/_authenticated/ca/grow'
    | '/_authenticated/ca/gst-library'
    | '/_authenticated/ca/help'
    | '/_authenticated/ca/reports'
    | '/_authenticated/ca/settings'
    | '/_authenticated/ca/staff'
    | '/_authenticated/ca/tasks'
    | '/_authenticated/ca/timesheets'
    | '/_authenticated/ca/vault'
    | '/_authenticated/client/agreements'
    | '/_authenticated/client/dashboard'
    | '/_authenticated/client/documents'
    | '/_authenticated/client/requests'
    | '/_authenticated/client/upload'
    | '/_authenticated/ca/'
    | '/_authenticated/client/'
    | '/_authenticated/ca/agreements/$agreementId'
    | '/_authenticated/ca/agreements/new'
    | '/_authenticated/ca/billing/$invoiceId'
    | '/_authenticated/ca/billing/new'
    | '/_authenticated/ca/billing/reports'
    | '/_authenticated/ca/billing/services'
    | '/_authenticated/ca/clients/$clientId'
    | '/_authenticated/ca/my-profile/cpe'
    | '/_authenticated/ca/reports/timesheets'
    | '/_authenticated/ca/settings/agreement-templates'
    | '/_authenticated/ca/settings/billing'
    | '/_authenticated/ca/settings/billing-subscription'
    | '/_authenticated/ca/settings/e-invoice'
    | '/_authenticated/ca/settings/referral'
    | '/_authenticated/ca/settings/tally-mappings'
    | '/_authenticated/ca/staff/$userId'
    | '/_authenticated/ca/tasks/my-tasks'
    | '/_authenticated/ca/timesheets/my-timesheet'
    | '/_authenticated/client/dashboard/compliance'
    | '/_authenticated/client/dashboard/filings'
    | '/_authenticated/client/dashboard/home'
    | '/_authenticated/client/dashboard/invoices'
    | '/_authenticated/client/dashboard/profile'
    | '/_authenticated/client/dashboard/queries'
    | '/_authenticated/client/dashboard/tasks'
    | '/_authenticated/client/dashboard/'
    | '/_authenticated/ca/agreements/$agreementId/edit'
    | '/_authenticated/ca/billing/$invoiceId/edit'
    | '/_authenticated/ca/clients/$clientId/compliance'
    | '/_authenticated/ca/clients/$clientId/documents'
    | '/_authenticated/ca/clients/$clientId/e-invoices'
    | '/_authenticated/ca/clients/$clientId/tally-export'
    | '/_authenticated/ca/clients/$clientId/tally-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRouteWithChildren
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/ca': {
      id: '/signup/ca'
      path: '/ca'
      fullPath: '/signup/ca'
      preLoaderRoute: typeof SignupCaRouteImport
      parentRoute: typeof SignupRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ca': {
      id: '/_authenticated/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof AuthenticatedCaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/ca/': {
      id: '/_authenticated/ca/'
      path: '/'
      fullPath: '/ca/'
      preLoaderRoute: typeof AuthenticatedCaIndexRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/client/upload': {
      id: '/_authenticated/client/upload'
      path: '/upload'
      fullPath: '/client/upload'
      preLoaderRoute: typeof AuthenticatedClientUploadRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/requests': {
      id: '/_authenticated/client/requests'
      path: '/requests'
      fullPath: '/client/requests'
      preLoaderRoute: typeof AuthenticatedClientRequestsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/documents': {
      id: '/_authenticated/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/dashboard': {
      id: '/_authenticated/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/agreements': {
      id: '/_authenticated/client/agreements'
      path: '/agreements'
      fullPath: '/client/agreements'
      preLoaderRoute: typeof AuthenticatedClientAgreementsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/ca/vault': {
      id: '/_authenticated/ca/vault'
      path: '/vault'
      fullPath: '/ca/vault'
      preLoaderRoute: typeof AuthenticatedCaVaultRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/timesheets': {
      id: '/_authenticated/ca/timesheets'
      path: '/timesheets'
      fullPath: '/ca/timesheets'
      preLoaderRoute: typeof AuthenticatedCaTimesheetsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/tasks': {
      id: '/_authenticated/ca/tasks'
      path: '/tasks'
      fullPath: '/ca/tasks'
      preLoaderRoute: typeof AuthenticatedCaTasksRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/staff': {
      id: '/_authenticated/ca/staff'
      path: '/staff'
      fullPath: '/ca/staff'
      preLoaderRoute: typeof AuthenticatedCaStaffRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/settings': {
      id: '/_authenticated/ca/settings'
      path: '/settings'
      fullPath: '/ca/settings'
      preLoaderRoute: typeof AuthenticatedCaSettingsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/reports': {
      id: '/_authenticated/ca/reports'
      path: '/reports'
      fullPath: '/ca/reports'
      preLoaderRoute: typeof AuthenticatedCaReportsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/help': {
      id: '/_authenticated/ca/help'
      path: '/help'
      fullPath: '/ca/help'
      preLoaderRoute: typeof AuthenticatedCaHelpRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/gst-library': {
      id: '/_authenticated/ca/gst-library'
      path: '/gst-library'
      fullPath: '/ca/gst-library'
      preLoaderRoute: typeof AuthenticatedCaGstLibraryRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/grow': {
      id: '/_authenticated/ca/grow'
      path: '/grow'
      fullPath: '/ca/grow'
      preLoaderRoute: typeof AuthenticatedCaGrowRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/e-invoices': {
      id: '/_authenticated/ca/e-invoices'
      path: '/e-invoices'
      fullPath: '/ca/e-invoices'
      preLoaderRoute: typeof AuthenticatedCaEInvoicesRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/dsc-vault': {
      id: '/_authenticated/ca/dsc-vault'
      path: '/dsc-vault'
      fullPath: '/ca/dsc-vault'
      preLoaderRoute: typeof AuthenticatedCaDscVaultRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/dashboard': {
      id: '/_authenticated/ca/dashboard'
      path: '/dashboard'
      fullPath: '/ca/dashboard'
      preLoaderRoute: typeof AuthenticatedCaDashboardRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/compliance-calendar': {
      id: '/_authenticated/ca/compliance-calendar'
      path: '/compliance-calendar'
      fullPath: '/ca/compliance-calendar'
      preLoaderRoute: typeof AuthenticatedCaComplianceCalendarRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/communications': {
      id: '/_authenticated/ca/communications'
      path: '/communications'
      fullPath: '/ca/communications'
      preLoaderRoute: typeof AuthenticatedCaCommunicationsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/clients': {
      id: '/_authenticated/ca/clients'
      path: '/clients'
      fullPath: '/ca/clients'
      preLoaderRoute: typeof AuthenticatedCaClientsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/billing': {
      id: '/_authenticated/ca/billing'
      path: '/billing'
      fullPath: '/ca/billing'
      preLoaderRoute: typeof AuthenticatedCaBillingRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/analytics': {
      id: '/_authenticated/ca/analytics'
      path: '/analytics'
      fullPath: '/ca/analytics'
      preLoaderRoute: typeof AuthenticatedCaAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/agreements': {
      id: '/_authenticated/ca/agreements'
      path: '/agreements'
      fullPath: '/ca/agreements'
      preLoaderRoute: typeof AuthenticatedCaAgreementsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/dashboard/': {
      id: '/_authenticated/client/dashboard/'
      path: '/'
      fullPath: '/client/dashboard/'
      preLoaderRoute: typeof AuthenticatedClientDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/tasks': {
      id: '/_authenticated/client/dashboard/tasks'
      path: '/tasks'
      fullPath: '/client/dashboard/tasks'
      preLoaderRoute: typeof AuthenticatedClientDashboardTasksRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/queries': {
      id: '/_authenticated/client/dashboard/queries'
      path: '/queries'
      fullPath: '/client/dashboard/queries'
      preLoaderRoute: typeof AuthenticatedClientDashboardQueriesRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/profile': {
      id: '/_authenticated/client/dashboard/profile'
      path: '/profile'
      fullPath: '/client/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedClientDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/invoices': {
      id: '/_authenticated/client/dashboard/invoices'
      path: '/invoices'
      fullPath: '/client/dashboard/invoices'
      preLoaderRoute: typeof AuthenticatedClientDashboardInvoicesRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/home': {
      id: '/_authenticated/client/dashboard/home'
      path: '/home'
      fullPath: '/client/dashboard/home'
      preLoaderRoute: typeof AuthenticatedClientDashboardHomeRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/filings': {
      id: '/_authenticated/client/dashboard/filings'
      path: '/filings'
      fullPath: '/client/dashboard/filings'
      preLoaderRoute: typeof AuthenticatedClientDashboardFilingsRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/client/dashboard/compliance': {
      id: '/_authenticated/client/dashboard/compliance'
      path: '/compliance'
      fullPath: '/client/dashboard/compliance'
      preLoaderRoute: typeof AuthenticatedClientDashboardComplianceRouteImport
      parentRoute: typeof AuthenticatedClientDashboardRoute
    }
    '/_authenticated/ca/timesheets/my-timesheet': {
      id: '/_authenticated/ca/timesheets/my-timesheet'
      path: '/my-timesheet'
      fullPath: '/ca/timesheets/my-timesheet'
      preLoaderRoute: typeof AuthenticatedCaTimesheetsMyTimesheetRouteImport
      parentRoute: typeof AuthenticatedCaTimesheetsRoute
    }
    '/_authenticated/ca/tasks/my-tasks': {
      id: '/_authenticated/ca/tasks/my-tasks'
      path: '/my-tasks'
      fullPath: '/ca/tasks/my-tasks'
      preLoaderRoute: typeof AuthenticatedCaTasksMyTasksRouteImport
      parentRoute: typeof AuthenticatedCaTasksRoute
    }
    '/_authenticated/ca/staff/$userId': {
      id: '/_authenticated/ca/staff/$userId'
      path: '/$userId'
      fullPath: '/ca/staff/$userId'
      preLoaderRoute: typeof AuthenticatedCaStaffUserIdRouteImport
      parentRoute: typeof AuthenticatedCaStaffRoute
    }
    '/_authenticated/ca/settings/tally-mappings': {
      id: '/_authenticated/ca/settings/tally-mappings'
      path: '/tally-mappings'
      fullPath: '/ca/settings/tally-mappings'
      preLoaderRoute: typeof AuthenticatedCaSettingsTallyMappingsRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/settings/referral': {
      id: '/_authenticated/ca/settings/referral'
      path: '/referral'
      fullPath: '/ca/settings/referral'
      preLoaderRoute: typeof AuthenticatedCaSettingsReferralRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/settings/e-invoice': {
      id: '/_authenticated/ca/settings/e-invoice'
      path: '/e-invoice'
      fullPath: '/ca/settings/e-invoice'
      preLoaderRoute: typeof AuthenticatedCaSettingsEInvoiceRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/settings/billing-subscription': {
      id: '/_authenticated/ca/settings/billing-subscription'
      path: '/billing-subscription'
      fullPath: '/ca/settings/billing-subscription'
      preLoaderRoute: typeof AuthenticatedCaSettingsBillingSubscriptionRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/settings/billing': {
      id: '/_authenticated/ca/settings/billing'
      path: '/billing'
      fullPath: '/ca/settings/billing'
      preLoaderRoute: typeof AuthenticatedCaSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/settings/agreement-templates': {
      id: '/_authenticated/ca/settings/agreement-templates'
      path: '/agreement-templates'
      fullPath: '/ca/settings/agreement-templates'
      preLoaderRoute: typeof AuthenticatedCaSettingsAgreementTemplatesRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/reports/timesheets': {
      id: '/_authenticated/ca/reports/timesheets'
      path: '/timesheets'
      fullPath: '/ca/reports/timesheets'
      preLoaderRoute: typeof AuthenticatedCaReportsTimesheetsRouteImport
      parentRoute: typeof AuthenticatedCaReportsRoute
    }
    '/_authenticated/ca/my-profile/cpe': {
      id: '/_authenticated/ca/my-profile/cpe'
      path: '/my-profile/cpe'
      fullPath: '/ca/my-profile/cpe'
      preLoaderRoute: typeof AuthenticatedCaMyProfileCpeRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/clients/$clientId': {
      id: '/_authenticated/ca/clients/$clientId'
      path: '/$clientId'
      fullPath: '/ca/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedCaClientsRoute
    }
    '/_authenticated/ca/billing/services': {
      id: '/_authenticated/ca/billing/services'
      path: '/services'
      fullPath: '/ca/billing/services'
      preLoaderRoute: typeof AuthenticatedCaBillingServicesRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/billing/reports': {
      id: '/_authenticated/ca/billing/reports'
      path: '/reports'
      fullPath: '/ca/billing/reports'
      preLoaderRoute: typeof AuthenticatedCaBillingReportsRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/billing/new': {
      id: '/_authenticated/ca/billing/new'
      path: '/new'
      fullPath: '/ca/billing/new'
      preLoaderRoute: typeof AuthenticatedCaBillingNewRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/billing/$invoiceId': {
      id: '/_authenticated/ca/billing/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/ca/billing/$invoiceId'
      preLoaderRoute: typeof AuthenticatedCaBillingInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/agreements/new': {
      id: '/_authenticated/ca/agreements/new'
      path: '/new'
      fullPath: '/ca/agreements/new'
      preLoaderRoute: typeof AuthenticatedCaAgreementsNewRouteImport
      parentRoute: typeof AuthenticatedCaAgreementsRoute
    }
    '/_authenticated/ca/agreements/$agreementId': {
      id: '/_authenticated/ca/agreements/$agreementId'
      path: '/$agreementId'
      fullPath: '/ca/agreements/$agreementId'
      preLoaderRoute: typeof AuthenticatedCaAgreementsAgreementIdRouteImport
      parentRoute: typeof AuthenticatedCaAgreementsRoute
    }
    '/_authenticated/ca/clients/$clientId/tally-import': {
      id: '/_authenticated/ca/clients/$clientId/tally-import'
      path: '/tally-import'
      fullPath: '/ca/clients/$clientId/tally-import'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdTallyImportRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/clients/$clientId/tally-export': {
      id: '/_authenticated/ca/clients/$clientId/tally-export'
      path: '/tally-export'
      fullPath: '/ca/clients/$clientId/tally-export'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdTallyExportRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/clients/$clientId/e-invoices': {
      id: '/_authenticated/ca/clients/$clientId/e-invoices'
      path: '/e-invoices'
      fullPath: '/ca/clients/$clientId/e-invoices'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdEInvoicesRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/clients/$clientId/documents': {
      id: '/_authenticated/ca/clients/$clientId/documents'
      path: '/documents'
      fullPath: '/ca/clients/$clientId/documents'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/clients/$clientId/compliance': {
      id: '/_authenticated/ca/clients/$clientId/compliance'
      path: '/compliance'
      fullPath: '/ca/clients/$clientId/compliance'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdComplianceRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/billing/$invoiceId/edit': {
      id: '/_authenticated/ca/billing/$invoiceId/edit'
      path: '/edit'
      fullPath: '/ca/billing/$invoiceId/edit'
      preLoaderRoute: typeof AuthenticatedCaBillingInvoiceIdEditRouteImport
      parentRoute: typeof AuthenticatedCaBillingInvoiceIdRoute
    }
    '/_authenticated/ca/agreements/$agreementId/edit': {
      id: '/_authenticated/ca/agreements/$agreementId/edit'
      path: '/edit'
      fullPath: '/ca/agreements/$agreementId/edit'
      preLoaderRoute: typeof AuthenticatedCaAgreementsAgreementIdEditRouteImport
      parentRoute: typeof AuthenticatedCaAgreementsAgreementIdRoute
    }
  }
}

interface AuthenticatedCaAgreementsAgreementIdRouteChildren {
  AuthenticatedCaAgreementsAgreementIdEditRoute: typeof AuthenticatedCaAgreementsAgreementIdEditRoute
}

const AuthenticatedCaAgreementsAgreementIdRouteChildren: AuthenticatedCaAgreementsAgreementIdRouteChildren =
  {
    AuthenticatedCaAgreementsAgreementIdEditRoute:
      AuthenticatedCaAgreementsAgreementIdEditRoute,
  }

const AuthenticatedCaAgreementsAgreementIdRouteWithChildren =
  AuthenticatedCaAgreementsAgreementIdRoute._addFileChildren(
    AuthenticatedCaAgreementsAgreementIdRouteChildren,
  )

interface AuthenticatedCaAgreementsRouteChildren {
  AuthenticatedCaAgreementsAgreementIdRoute: typeof AuthenticatedCaAgreementsAgreementIdRouteWithChildren
  AuthenticatedCaAgreementsNewRoute: typeof AuthenticatedCaAgreementsNewRoute
}

const AuthenticatedCaAgreementsRouteChildren: AuthenticatedCaAgreementsRouteChildren =
  {
    AuthenticatedCaAgreementsAgreementIdRoute:
      AuthenticatedCaAgreementsAgreementIdRouteWithChildren,
    AuthenticatedCaAgreementsNewRoute: AuthenticatedCaAgreementsNewRoute,
  }

const AuthenticatedCaAgreementsRouteWithChildren =
  AuthenticatedCaAgreementsRoute._addFileChildren(
    AuthenticatedCaAgreementsRouteChildren,
  )

interface AuthenticatedCaBillingInvoiceIdRouteChildren {
  AuthenticatedCaBillingInvoiceIdEditRoute: typeof AuthenticatedCaBillingInvoiceIdEditRoute
}

const AuthenticatedCaBillingInvoiceIdRouteChildren: AuthenticatedCaBillingInvoiceIdRouteChildren =
  {
    AuthenticatedCaBillingInvoiceIdEditRoute:
      AuthenticatedCaBillingInvoiceIdEditRoute,
  }

const AuthenticatedCaBillingInvoiceIdRouteWithChildren =
  AuthenticatedCaBillingInvoiceIdRoute._addFileChildren(
    AuthenticatedCaBillingInvoiceIdRouteChildren,
  )

interface AuthenticatedCaBillingRouteChildren {
  AuthenticatedCaBillingInvoiceIdRoute: typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  AuthenticatedCaBillingNewRoute: typeof AuthenticatedCaBillingNewRoute
  AuthenticatedCaBillingReportsRoute: typeof AuthenticatedCaBillingReportsRoute
  AuthenticatedCaBillingServicesRoute: typeof AuthenticatedCaBillingServicesRoute
}

const AuthenticatedCaBillingRouteChildren: AuthenticatedCaBillingRouteChildren =
  {
    AuthenticatedCaBillingInvoiceIdRoute:
      AuthenticatedCaBillingInvoiceIdRouteWithChildren,
    AuthenticatedCaBillingNewRoute: AuthenticatedCaBillingNewRoute,
    AuthenticatedCaBillingReportsRoute: AuthenticatedCaBillingReportsRoute,
    AuthenticatedCaBillingServicesRoute: AuthenticatedCaBillingServicesRoute,
  }

const AuthenticatedCaBillingRouteWithChildren =
  AuthenticatedCaBillingRoute._addFileChildren(
    AuthenticatedCaBillingRouteChildren,
  )

interface AuthenticatedCaClientsClientIdRouteChildren {
  AuthenticatedCaClientsClientIdComplianceRoute: typeof AuthenticatedCaClientsClientIdComplianceRoute
  AuthenticatedCaClientsClientIdDocumentsRoute: typeof AuthenticatedCaClientsClientIdDocumentsRoute
  AuthenticatedCaClientsClientIdEInvoicesRoute: typeof AuthenticatedCaClientsClientIdEInvoicesRoute
  AuthenticatedCaClientsClientIdTallyExportRoute: typeof AuthenticatedCaClientsClientIdTallyExportRoute
  AuthenticatedCaClientsClientIdTallyImportRoute: typeof AuthenticatedCaClientsClientIdTallyImportRoute
}

const AuthenticatedCaClientsClientIdRouteChildren: AuthenticatedCaClientsClientIdRouteChildren =
  {
    AuthenticatedCaClientsClientIdComplianceRoute:
      AuthenticatedCaClientsClientIdComplianceRoute,
    AuthenticatedCaClientsClientIdDocumentsRoute:
      AuthenticatedCaClientsClientIdDocumentsRoute,
    AuthenticatedCaClientsClientIdEInvoicesRoute:
      AuthenticatedCaClientsClientIdEInvoicesRoute,
    AuthenticatedCaClientsClientIdTallyExportRoute:
      AuthenticatedCaClientsClientIdTallyExportRoute,
    AuthenticatedCaClientsClientIdTallyImportRoute:
      AuthenticatedCaClientsClientIdTallyImportRoute,
  }

const AuthenticatedCaClientsClientIdRouteWithChildren =
  AuthenticatedCaClientsClientIdRoute._addFileChildren(
    AuthenticatedCaClientsClientIdRouteChildren,
  )

interface AuthenticatedCaClientsRouteChildren {
  AuthenticatedCaClientsClientIdRoute: typeof AuthenticatedCaClientsClientIdRouteWithChildren
}

const AuthenticatedCaClientsRouteChildren: AuthenticatedCaClientsRouteChildren =
  {
    AuthenticatedCaClientsClientIdRoute:
      AuthenticatedCaClientsClientIdRouteWithChildren,
  }

const AuthenticatedCaClientsRouteWithChildren =
  AuthenticatedCaClientsRoute._addFileChildren(
    AuthenticatedCaClientsRouteChildren,
  )

interface AuthenticatedCaReportsRouteChildren {
  AuthenticatedCaReportsTimesheetsRoute: typeof AuthenticatedCaReportsTimesheetsRoute
}

const AuthenticatedCaReportsRouteChildren: AuthenticatedCaReportsRouteChildren =
  {
    AuthenticatedCaReportsTimesheetsRoute:
      AuthenticatedCaReportsTimesheetsRoute,
  }

const AuthenticatedCaReportsRouteWithChildren =
  AuthenticatedCaReportsRoute._addFileChildren(
    AuthenticatedCaReportsRouteChildren,
  )

interface AuthenticatedCaSettingsRouteChildren {
  AuthenticatedCaSettingsAgreementTemplatesRoute: typeof AuthenticatedCaSettingsAgreementTemplatesRoute
  AuthenticatedCaSettingsBillingRoute: typeof AuthenticatedCaSettingsBillingRoute
  AuthenticatedCaSettingsBillingSubscriptionRoute: typeof AuthenticatedCaSettingsBillingSubscriptionRoute
  AuthenticatedCaSettingsEInvoiceRoute: typeof AuthenticatedCaSettingsEInvoiceRoute
  AuthenticatedCaSettingsReferralRoute: typeof AuthenticatedCaSettingsReferralRoute
  AuthenticatedCaSettingsTallyMappingsRoute: typeof AuthenticatedCaSettingsTallyMappingsRoute
}

const AuthenticatedCaSettingsRouteChildren: AuthenticatedCaSettingsRouteChildren =
  {
    AuthenticatedCaSettingsAgreementTemplatesRoute:
      AuthenticatedCaSettingsAgreementTemplatesRoute,
    AuthenticatedCaSettingsBillingRoute: AuthenticatedCaSettingsBillingRoute,
    AuthenticatedCaSettingsBillingSubscriptionRoute:
      AuthenticatedCaSettingsBillingSubscriptionRoute,
    AuthenticatedCaSettingsEInvoiceRoute: AuthenticatedCaSettingsEInvoiceRoute,
    AuthenticatedCaSettingsReferralRoute: AuthenticatedCaSettingsReferralRoute,
    AuthenticatedCaSettingsTallyMappingsRoute:
      AuthenticatedCaSettingsTallyMappingsRoute,
  }

const AuthenticatedCaSettingsRouteWithChildren =
  AuthenticatedCaSettingsRoute._addFileChildren(
    AuthenticatedCaSettingsRouteChildren,
  )

interface AuthenticatedCaStaffRouteChildren {
  AuthenticatedCaStaffUserIdRoute: typeof AuthenticatedCaStaffUserIdRoute
}

const AuthenticatedCaStaffRouteChildren: AuthenticatedCaStaffRouteChildren = {
  AuthenticatedCaStaffUserIdRoute: AuthenticatedCaStaffUserIdRoute,
}

const AuthenticatedCaStaffRouteWithChildren =
  AuthenticatedCaStaffRoute._addFileChildren(AuthenticatedCaStaffRouteChildren)

interface AuthenticatedCaTasksRouteChildren {
  AuthenticatedCaTasksMyTasksRoute: typeof AuthenticatedCaTasksMyTasksRoute
}

const AuthenticatedCaTasksRouteChildren: AuthenticatedCaTasksRouteChildren = {
  AuthenticatedCaTasksMyTasksRoute: AuthenticatedCaTasksMyTasksRoute,
}

const AuthenticatedCaTasksRouteWithChildren =
  AuthenticatedCaTasksRoute._addFileChildren(AuthenticatedCaTasksRouteChildren)

interface AuthenticatedCaTimesheetsRouteChildren {
  AuthenticatedCaTimesheetsMyTimesheetRoute: typeof AuthenticatedCaTimesheetsMyTimesheetRoute
}

const AuthenticatedCaTimesheetsRouteChildren: AuthenticatedCaTimesheetsRouteChildren =
  {
    AuthenticatedCaTimesheetsMyTimesheetRoute:
      AuthenticatedCaTimesheetsMyTimesheetRoute,
  }

const AuthenticatedCaTimesheetsRouteWithChildren =
  AuthenticatedCaTimesheetsRoute._addFileChildren(
    AuthenticatedCaTimesheetsRouteChildren,
  )

interface AuthenticatedCaRouteChildren {
  AuthenticatedCaAgreementsRoute: typeof AuthenticatedCaAgreementsRouteWithChildren
  AuthenticatedCaAnalyticsRoute: typeof AuthenticatedCaAnalyticsRoute
  AuthenticatedCaBillingRoute: typeof AuthenticatedCaBillingRouteWithChildren
  AuthenticatedCaClientsRoute: typeof AuthenticatedCaClientsRouteWithChildren
  AuthenticatedCaCommunicationsRoute: typeof AuthenticatedCaCommunicationsRoute
  AuthenticatedCaComplianceCalendarRoute: typeof AuthenticatedCaComplianceCalendarRoute
  AuthenticatedCaDashboardRoute: typeof AuthenticatedCaDashboardRoute
  AuthenticatedCaDscVaultRoute: typeof AuthenticatedCaDscVaultRoute
  AuthenticatedCaEInvoicesRoute: typeof AuthenticatedCaEInvoicesRoute
  AuthenticatedCaGrowRoute: typeof AuthenticatedCaGrowRoute
  AuthenticatedCaGstLibraryRoute: typeof AuthenticatedCaGstLibraryRoute
  AuthenticatedCaHelpRoute: typeof AuthenticatedCaHelpRoute
  AuthenticatedCaReportsRoute: typeof AuthenticatedCaReportsRouteWithChildren
  AuthenticatedCaSettingsRoute: typeof AuthenticatedCaSettingsRouteWithChildren
  AuthenticatedCaStaffRoute: typeof AuthenticatedCaStaffRouteWithChildren
  AuthenticatedCaTasksRoute: typeof AuthenticatedCaTasksRouteWithChildren
  AuthenticatedCaTimesheetsRoute: typeof AuthenticatedCaTimesheetsRouteWithChildren
  AuthenticatedCaVaultRoute: typeof AuthenticatedCaVaultRoute
  AuthenticatedCaIndexRoute: typeof AuthenticatedCaIndexRoute
  AuthenticatedCaMyProfileCpeRoute: typeof AuthenticatedCaMyProfileCpeRoute
}

const AuthenticatedCaRouteChildren: AuthenticatedCaRouteChildren = {
  AuthenticatedCaAgreementsRoute: AuthenticatedCaAgreementsRouteWithChildren,
  AuthenticatedCaAnalyticsRoute: AuthenticatedCaAnalyticsRoute,
  AuthenticatedCaBillingRoute: AuthenticatedCaBillingRouteWithChildren,
  AuthenticatedCaClientsRoute: AuthenticatedCaClientsRouteWithChildren,
  AuthenticatedCaCommunicationsRoute: AuthenticatedCaCommunicationsRoute,
  AuthenticatedCaComplianceCalendarRoute:
    AuthenticatedCaComplianceCalendarRoute,
  AuthenticatedCaDashboardRoute: AuthenticatedCaDashboardRoute,
  AuthenticatedCaDscVaultRoute: AuthenticatedCaDscVaultRoute,
  AuthenticatedCaEInvoicesRoute: AuthenticatedCaEInvoicesRoute,
  AuthenticatedCaGrowRoute: AuthenticatedCaGrowRoute,
  AuthenticatedCaGstLibraryRoute: AuthenticatedCaGstLibraryRoute,
  AuthenticatedCaHelpRoute: AuthenticatedCaHelpRoute,
  AuthenticatedCaReportsRoute: AuthenticatedCaReportsRouteWithChildren,
  AuthenticatedCaSettingsRoute: AuthenticatedCaSettingsRouteWithChildren,
  AuthenticatedCaStaffRoute: AuthenticatedCaStaffRouteWithChildren,
  AuthenticatedCaTasksRoute: AuthenticatedCaTasksRouteWithChildren,
  AuthenticatedCaTimesheetsRoute: AuthenticatedCaTimesheetsRouteWithChildren,
  AuthenticatedCaVaultRoute: AuthenticatedCaVaultRoute,
  AuthenticatedCaIndexRoute: AuthenticatedCaIndexRoute,
  AuthenticatedCaMyProfileCpeRoute: AuthenticatedCaMyProfileCpeRoute,
}

const AuthenticatedCaRouteWithChildren = AuthenticatedCaRoute._addFileChildren(
  AuthenticatedCaRouteChildren,
)

interface AuthenticatedClientDashboardRouteChildren {
  AuthenticatedClientDashboardComplianceRoute: typeof AuthenticatedClientDashboardComplianceRoute
  AuthenticatedClientDashboardFilingsRoute: typeof AuthenticatedClientDashboardFilingsRoute
  AuthenticatedClientDashboardHomeRoute: typeof AuthenticatedClientDashboardHomeRoute
  AuthenticatedClientDashboardInvoicesRoute: typeof AuthenticatedClientDashboardInvoicesRoute
  AuthenticatedClientDashboardProfileRoute: typeof AuthenticatedClientDashboardProfileRoute
  AuthenticatedClientDashboardQueriesRoute: typeof AuthenticatedClientDashboardQueriesRoute
  AuthenticatedClientDashboardTasksRoute: typeof AuthenticatedClientDashboardTasksRoute
  AuthenticatedClientDashboardIndexRoute: typeof AuthenticatedClientDashboardIndexRoute
}

const AuthenticatedClientDashboardRouteChildren: AuthenticatedClientDashboardRouteChildren =
  {
    AuthenticatedClientDashboardComplianceRoute:
      AuthenticatedClientDashboardComplianceRoute,
    AuthenticatedClientDashboardFilingsRoute:
      AuthenticatedClientDashboardFilingsRoute,
    AuthenticatedClientDashboardHomeRoute:
      AuthenticatedClientDashboardHomeRoute,
    AuthenticatedClientDashboardInvoicesRoute:
      AuthenticatedClientDashboardInvoicesRoute,
    AuthenticatedClientDashboardProfileRoute:
      AuthenticatedClientDashboardProfileRoute,
    AuthenticatedClientDashboardQueriesRoute:
      AuthenticatedClientDashboardQueriesRoute,
    AuthenticatedClientDashboardTasksRoute:
      AuthenticatedClientDashboardTasksRoute,
    AuthenticatedClientDashboardIndexRoute:
      AuthenticatedClientDashboardIndexRoute,
  }

const AuthenticatedClientDashboardRouteWithChildren =
  AuthenticatedClientDashboardRoute._addFileChildren(
    AuthenticatedClientDashboardRouteChildren,
  )

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientAgreementsRoute: typeof AuthenticatedClientAgreementsRoute
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRouteWithChildren
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientRequestsRoute: typeof AuthenticatedClientRequestsRoute
  AuthenticatedClientUploadRoute: typeof AuthenticatedClientUploadRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientAgreementsRoute: AuthenticatedClientAgreementsRoute,
  AuthenticatedClientDashboardRoute:
    AuthenticatedClientDashboardRouteWithChildren,
  AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
  AuthenticatedClientRequestsRoute: AuthenticatedClientRequestsRoute,
  AuthenticatedClientUploadRoute: AuthenticatedClientUploadRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCaRoute: typeof AuthenticatedCaRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCaRoute: AuthenticatedCaRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SignupRouteChildren {
  SignupCaRoute: typeof SignupCaRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCaRoute: SignupCaRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRouteWithChildren,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
