/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupCaRouteImport } from './routes/signup.ca'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedCaRouteImport } from './routes/_authenticated/ca'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedCaIndexRouteImport } from './routes/_authenticated/ca.index'
import { Route as AuthenticatedClientUploadRouteImport } from './routes/_authenticated/client.upload'
import { Route as AuthenticatedClientRequestsRouteImport } from './routes/_authenticated/client.requests'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/client.dashboard'
import { Route as AuthenticatedCaSettingsRouteImport } from './routes/_authenticated/ca.settings'
import { Route as AuthenticatedCaReportsRouteImport } from './routes/_authenticated/ca.reports'
import { Route as AuthenticatedCaDashboardRouteImport } from './routes/_authenticated/ca.dashboard'
import { Route as AuthenticatedCaComplianceCalendarRouteImport } from './routes/_authenticated/ca.compliance-calendar'
import { Route as AuthenticatedCaClientsRouteImport } from './routes/_authenticated/ca.clients'
import { Route as AuthenticatedCaClientsClientIdRouteImport } from './routes/_authenticated/ca.clients.$clientId'
import { Route as AuthenticatedCaClientsClientIdComplianceRouteImport } from './routes/_authenticated/ca.clients.$clientId.compliance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCaRoute = SignupCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => SignupRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaRoute = AuthenticatedCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedCaIndexRoute = AuthenticatedCaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedClientUploadRoute =
  AuthenticatedClientUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientRequestsRoute =
  AuthenticatedClientRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedCaSettingsRoute = AuthenticatedCaSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaReportsRoute = AuthenticatedCaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaDashboardRoute =
  AuthenticatedCaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaComplianceCalendarRoute =
  AuthenticatedCaComplianceCalendarRouteImport.update({
    id: '/compliance-calendar',
    path: '/compliance-calendar',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaClientsRoute = AuthenticatedCaClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaClientsClientIdRoute =
  AuthenticatedCaClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedCaClientsRoute,
  } as any)
const AuthenticatedCaClientsClientIdComplianceRoute =
  AuthenticatedCaClientsClientIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/ca': typeof AuthenticatedCaRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup/': typeof SignupIndexRoute
  '/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/ca/reports': typeof AuthenticatedCaReportsRoute
  '/ca/settings': typeof AuthenticatedCaSettingsRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/requests': typeof AuthenticatedClientRequestsRoute
  '/client/upload': typeof AuthenticatedClientUploadRoute
  '/ca/': typeof AuthenticatedCaIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup': typeof SignupIndexRoute
  '/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/ca/reports': typeof AuthenticatedCaReportsRoute
  '/ca/settings': typeof AuthenticatedCaSettingsRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/requests': typeof AuthenticatedClientRequestsRoute
  '/client/upload': typeof AuthenticatedClientUploadRoute
  '/ca': typeof AuthenticatedCaIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/ca': typeof AuthenticatedCaRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/_authenticated/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/_authenticated/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/_authenticated/ca/reports': typeof AuthenticatedCaReportsRoute
  '/_authenticated/ca/settings': typeof AuthenticatedCaSettingsRoute
  '/_authenticated/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/client/requests': typeof AuthenticatedClientRequestsRoute
  '/_authenticated/client/upload': typeof AuthenticatedClientUploadRoute
  '/_authenticated/ca/': typeof AuthenticatedCaIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/_authenticated/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/assistant'
    | '/ca'
    | '/client'
    | '/dashboard'
    | '/invoices'
    | '/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/signup/ca'
    | '/signup/'
    | '/ca/clients'
    | '/ca/compliance-calendar'
    | '/ca/dashboard'
    | '/ca/reports'
    | '/ca/settings'
    | '/client/dashboard'
    | '/client/requests'
    | '/client/upload'
    | '/ca/'
    | '/client/'
    | '/ca/clients/$clientId'
    | '/ca/clients/$clientId/compliance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assistant'
    | '/dashboard'
    | '/invoices'
    | '/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/signup/ca'
    | '/signup'
    | '/ca/clients'
    | '/ca/compliance-calendar'
    | '/ca/dashboard'
    | '/ca/reports'
    | '/ca/settings'
    | '/client/dashboard'
    | '/client/requests'
    | '/client/upload'
    | '/ca'
    | '/client'
    | '/ca/clients/$clientId'
    | '/ca/clients/$clientId/compliance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/assistant'
    | '/_authenticated/ca'
    | '/_authenticated/client'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/signup/ca'
    | '/signup/'
    | '/_authenticated/ca/clients'
    | '/_authenticated/ca/compliance-calendar'
    | '/_authenticated/ca/dashboard'
    | '/_authenticated/ca/reports'
    | '/_authenticated/ca/settings'
    | '/_authenticated/client/dashboard'
    | '/_authenticated/client/requests'
    | '/_authenticated/client/upload'
    | '/_authenticated/ca/'
    | '/_authenticated/client/'
    | '/_authenticated/ca/clients/$clientId'
    | '/_authenticated/ca/clients/$clientId/compliance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRouteWithChildren
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/ca': {
      id: '/signup/ca'
      path: '/ca'
      fullPath: '/signup/ca'
      preLoaderRoute: typeof SignupCaRouteImport
      parentRoute: typeof SignupRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ca': {
      id: '/_authenticated/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof AuthenticatedCaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/ca/': {
      id: '/_authenticated/ca/'
      path: '/'
      fullPath: '/ca/'
      preLoaderRoute: typeof AuthenticatedCaIndexRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/client/upload': {
      id: '/_authenticated/client/upload'
      path: '/upload'
      fullPath: '/client/upload'
      preLoaderRoute: typeof AuthenticatedClientUploadRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/requests': {
      id: '/_authenticated/client/requests'
      path: '/requests'
      fullPath: '/client/requests'
      preLoaderRoute: typeof AuthenticatedClientRequestsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/dashboard': {
      id: '/_authenticated/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/ca/settings': {
      id: '/_authenticated/ca/settings'
      path: '/settings'
      fullPath: '/ca/settings'
      preLoaderRoute: typeof AuthenticatedCaSettingsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/reports': {
      id: '/_authenticated/ca/reports'
      path: '/reports'
      fullPath: '/ca/reports'
      preLoaderRoute: typeof AuthenticatedCaReportsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/dashboard': {
      id: '/_authenticated/ca/dashboard'
      path: '/dashboard'
      fullPath: '/ca/dashboard'
      preLoaderRoute: typeof AuthenticatedCaDashboardRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/compliance-calendar': {
      id: '/_authenticated/ca/compliance-calendar'
      path: '/compliance-calendar'
      fullPath: '/ca/compliance-calendar'
      preLoaderRoute: typeof AuthenticatedCaComplianceCalendarRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/clients': {
      id: '/_authenticated/ca/clients'
      path: '/clients'
      fullPath: '/ca/clients'
      preLoaderRoute: typeof AuthenticatedCaClientsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/clients/$clientId': {
      id: '/_authenticated/ca/clients/$clientId'
      path: '/$clientId'
      fullPath: '/ca/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedCaClientsRoute
    }
    '/_authenticated/ca/clients/$clientId/compliance': {
      id: '/_authenticated/ca/clients/$clientId/compliance'
      path: '/compliance'
      fullPath: '/ca/clients/$clientId/compliance'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdComplianceRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
  }
}

interface AuthenticatedCaClientsClientIdRouteChildren {
  AuthenticatedCaClientsClientIdComplianceRoute: typeof AuthenticatedCaClientsClientIdComplianceRoute
}

const AuthenticatedCaClientsClientIdRouteChildren: AuthenticatedCaClientsClientIdRouteChildren =
  {
    AuthenticatedCaClientsClientIdComplianceRoute:
      AuthenticatedCaClientsClientIdComplianceRoute,
  }

const AuthenticatedCaClientsClientIdRouteWithChildren =
  AuthenticatedCaClientsClientIdRoute._addFileChildren(
    AuthenticatedCaClientsClientIdRouteChildren,
  )

interface AuthenticatedCaClientsRouteChildren {
  AuthenticatedCaClientsClientIdRoute: typeof AuthenticatedCaClientsClientIdRouteWithChildren
}

const AuthenticatedCaClientsRouteChildren: AuthenticatedCaClientsRouteChildren =
  {
    AuthenticatedCaClientsClientIdRoute:
      AuthenticatedCaClientsClientIdRouteWithChildren,
  }

const AuthenticatedCaClientsRouteWithChildren =
  AuthenticatedCaClientsRoute._addFileChildren(
    AuthenticatedCaClientsRouteChildren,
  )

interface AuthenticatedCaRouteChildren {
  AuthenticatedCaClientsRoute: typeof AuthenticatedCaClientsRouteWithChildren
  AuthenticatedCaComplianceCalendarRoute: typeof AuthenticatedCaComplianceCalendarRoute
  AuthenticatedCaDashboardRoute: typeof AuthenticatedCaDashboardRoute
  AuthenticatedCaReportsRoute: typeof AuthenticatedCaReportsRoute
  AuthenticatedCaSettingsRoute: typeof AuthenticatedCaSettingsRoute
  AuthenticatedCaIndexRoute: typeof AuthenticatedCaIndexRoute
}

const AuthenticatedCaRouteChildren: AuthenticatedCaRouteChildren = {
  AuthenticatedCaClientsRoute: AuthenticatedCaClientsRouteWithChildren,
  AuthenticatedCaComplianceCalendarRoute:
    AuthenticatedCaComplianceCalendarRoute,
  AuthenticatedCaDashboardRoute: AuthenticatedCaDashboardRoute,
  AuthenticatedCaReportsRoute: AuthenticatedCaReportsRoute,
  AuthenticatedCaSettingsRoute: AuthenticatedCaSettingsRoute,
  AuthenticatedCaIndexRoute: AuthenticatedCaIndexRoute,
}

const AuthenticatedCaRouteWithChildren = AuthenticatedCaRoute._addFileChildren(
  AuthenticatedCaRouteChildren,
)

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedClientRequestsRoute: typeof AuthenticatedClientRequestsRoute
  AuthenticatedClientUploadRoute: typeof AuthenticatedClientUploadRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedClientRequestsRoute: AuthenticatedClientRequestsRoute,
  AuthenticatedClientUploadRoute: AuthenticatedClientUploadRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCaRoute: typeof AuthenticatedCaRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCaRoute: AuthenticatedCaRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SignupRouteChildren {
  SignupCaRoute: typeof SignupCaRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCaRoute: SignupCaRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRouteWithChildren,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
