/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupCaRouteImport } from './routes/signup.ca'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedCaRouteImport } from './routes/_authenticated/ca'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client.index'
import { Route as AuthenticatedCaIndexRouteImport } from './routes/_authenticated/ca.index'
import { Route as AuthenticatedClientUploadRouteImport } from './routes/_authenticated/client.upload'
import { Route as AuthenticatedClientRequestsRouteImport } from './routes/_authenticated/client.requests'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/client.documents'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/client.dashboard'
import { Route as AuthenticatedCaVaultRouteImport } from './routes/_authenticated/ca.vault'
import { Route as AuthenticatedCaTimesheetsRouteImport } from './routes/_authenticated/ca.timesheets'
import { Route as AuthenticatedCaTasksRouteImport } from './routes/_authenticated/ca.tasks'
import { Route as AuthenticatedCaStaffRouteImport } from './routes/_authenticated/ca.staff'
import { Route as AuthenticatedCaSettingsRouteImport } from './routes/_authenticated/ca.settings'
import { Route as AuthenticatedCaReportsRouteImport } from './routes/_authenticated/ca.reports'
import { Route as AuthenticatedCaDscVaultRouteImport } from './routes/_authenticated/ca.dsc-vault'
import { Route as AuthenticatedCaDashboardRouteImport } from './routes/_authenticated/ca.dashboard'
import { Route as AuthenticatedCaComplianceCalendarRouteImport } from './routes/_authenticated/ca.compliance-calendar'
import { Route as AuthenticatedCaCommunicationsRouteImport } from './routes/_authenticated/ca.communications'
import { Route as AuthenticatedCaClientsRouteImport } from './routes/_authenticated/ca.clients'
import { Route as AuthenticatedCaBillingRouteImport } from './routes/_authenticated/ca.billing'
import { Route as AuthenticatedCaTimesheetsMyTimesheetRouteImport } from './routes/_authenticated/ca.timesheets.my-timesheet'
import { Route as AuthenticatedCaTasksMyTasksRouteImport } from './routes/_authenticated/ca.tasks.my-tasks'
import { Route as AuthenticatedCaStaffUserIdRouteImport } from './routes/_authenticated/ca.staff.$userId'
import { Route as AuthenticatedCaSettingsBillingRouteImport } from './routes/_authenticated/ca.settings.billing'
import { Route as AuthenticatedCaReportsTimesheetsRouteImport } from './routes/_authenticated/ca.reports.timesheets'
import { Route as AuthenticatedCaClientsClientIdRouteImport } from './routes/_authenticated/ca.clients.$clientId'
import { Route as AuthenticatedCaBillingServicesRouteImport } from './routes/_authenticated/ca.billing.services'
import { Route as AuthenticatedCaBillingReportsRouteImport } from './routes/_authenticated/ca.billing.reports'
import { Route as AuthenticatedCaBillingNewRouteImport } from './routes/_authenticated/ca.billing.new'
import { Route as AuthenticatedCaBillingInvoiceIdRouteImport } from './routes/_authenticated/ca.billing.$invoiceId'
import { Route as AuthenticatedCaClientsClientIdDocumentsRouteImport } from './routes/_authenticated/ca.clients.$clientId.documents'
import { Route as AuthenticatedCaClientsClientIdComplianceRouteImport } from './routes/_authenticated/ca.clients.$clientId.compliance'
import { Route as AuthenticatedCaBillingInvoiceIdEditRouteImport } from './routes/_authenticated/ca.billing.$invoiceId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCaRoute = SignupCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => SignupRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaRoute = AuthenticatedCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedCaIndexRoute = AuthenticatedCaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedClientUploadRoute =
  AuthenticatedClientUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientRequestsRoute =
  AuthenticatedClientRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedCaVaultRoute = AuthenticatedCaVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaTimesheetsRoute =
  AuthenticatedCaTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaTasksRoute = AuthenticatedCaTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaStaffRoute = AuthenticatedCaStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaSettingsRoute = AuthenticatedCaSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaReportsRoute = AuthenticatedCaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaDscVaultRoute = AuthenticatedCaDscVaultRouteImport.update({
  id: '/dsc-vault',
  path: '/dsc-vault',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaDashboardRoute =
  AuthenticatedCaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaComplianceCalendarRoute =
  AuthenticatedCaComplianceCalendarRouteImport.update({
    id: '/compliance-calendar',
    path: '/compliance-calendar',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaCommunicationsRoute =
  AuthenticatedCaCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedCaRoute,
  } as any)
const AuthenticatedCaClientsRoute = AuthenticatedCaClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaBillingRoute = AuthenticatedCaBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedCaRoute,
} as any)
const AuthenticatedCaTimesheetsMyTimesheetRoute =
  AuthenticatedCaTimesheetsMyTimesheetRouteImport.update({
    id: '/my-timesheet',
    path: '/my-timesheet',
    getParentRoute: () => AuthenticatedCaTimesheetsRoute,
  } as any)
const AuthenticatedCaTasksMyTasksRoute =
  AuthenticatedCaTasksMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedCaTasksRoute,
  } as any)
const AuthenticatedCaStaffUserIdRoute =
  AuthenticatedCaStaffUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedCaStaffRoute,
  } as any)
const AuthenticatedCaSettingsBillingRoute =
  AuthenticatedCaSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedCaSettingsRoute,
  } as any)
const AuthenticatedCaReportsTimesheetsRoute =
  AuthenticatedCaReportsTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => AuthenticatedCaReportsRoute,
  } as any)
const AuthenticatedCaClientsClientIdRoute =
  AuthenticatedCaClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedCaClientsRoute,
  } as any)
const AuthenticatedCaBillingServicesRoute =
  AuthenticatedCaBillingServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaBillingReportsRoute =
  AuthenticatedCaBillingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaBillingNewRoute =
  AuthenticatedCaBillingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaBillingInvoiceIdRoute =
  AuthenticatedCaBillingInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedCaBillingRoute,
  } as any)
const AuthenticatedCaClientsClientIdDocumentsRoute =
  AuthenticatedCaClientsClientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaClientsClientIdComplianceRoute =
  AuthenticatedCaClientsClientIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedCaClientsClientIdRoute,
  } as any)
const AuthenticatedCaBillingInvoiceIdEditRoute =
  AuthenticatedCaBillingInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedCaBillingInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/ca': typeof AuthenticatedCaRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup/': typeof SignupIndexRoute
  '/ca/billing': typeof AuthenticatedCaBillingRouteWithChildren
  '/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/ca/communications': typeof AuthenticatedCaCommunicationsRoute
  '/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/ca/dsc-vault': typeof AuthenticatedCaDscVaultRoute
  '/ca/reports': typeof AuthenticatedCaReportsRouteWithChildren
  '/ca/settings': typeof AuthenticatedCaSettingsRouteWithChildren
  '/ca/staff': typeof AuthenticatedCaStaffRouteWithChildren
  '/ca/tasks': typeof AuthenticatedCaTasksRouteWithChildren
  '/ca/timesheets': typeof AuthenticatedCaTimesheetsRouteWithChildren
  '/ca/vault': typeof AuthenticatedCaVaultRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/requests': typeof AuthenticatedClientRequestsRoute
  '/client/upload': typeof AuthenticatedClientUploadRoute
  '/ca/': typeof AuthenticatedCaIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/ca/billing/$invoiceId': typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  '/ca/billing/new': typeof AuthenticatedCaBillingNewRoute
  '/ca/billing/reports': typeof AuthenticatedCaBillingReportsRoute
  '/ca/billing/services': typeof AuthenticatedCaBillingServicesRoute
  '/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/ca/reports/timesheets': typeof AuthenticatedCaReportsTimesheetsRoute
  '/ca/settings/billing': typeof AuthenticatedCaSettingsBillingRoute
  '/ca/staff/$userId': typeof AuthenticatedCaStaffUserIdRoute
  '/ca/tasks/my-tasks': typeof AuthenticatedCaTasksMyTasksRoute
  '/ca/timesheets/my-timesheet': typeof AuthenticatedCaTimesheetsMyTimesheetRoute
  '/ca/billing/$invoiceId/edit': typeof AuthenticatedCaBillingInvoiceIdEditRoute
  '/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
  '/ca/clients/$clientId/documents': typeof AuthenticatedCaClientsClientIdDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup': typeof SignupIndexRoute
  '/ca/billing': typeof AuthenticatedCaBillingRouteWithChildren
  '/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/ca/communications': typeof AuthenticatedCaCommunicationsRoute
  '/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/ca/dsc-vault': typeof AuthenticatedCaDscVaultRoute
  '/ca/reports': typeof AuthenticatedCaReportsRouteWithChildren
  '/ca/settings': typeof AuthenticatedCaSettingsRouteWithChildren
  '/ca/staff': typeof AuthenticatedCaStaffRouteWithChildren
  '/ca/tasks': typeof AuthenticatedCaTasksRouteWithChildren
  '/ca/timesheets': typeof AuthenticatedCaTimesheetsRouteWithChildren
  '/ca/vault': typeof AuthenticatedCaVaultRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/requests': typeof AuthenticatedClientRequestsRoute
  '/client/upload': typeof AuthenticatedClientUploadRoute
  '/ca': typeof AuthenticatedCaIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/ca/billing/$invoiceId': typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  '/ca/billing/new': typeof AuthenticatedCaBillingNewRoute
  '/ca/billing/reports': typeof AuthenticatedCaBillingReportsRoute
  '/ca/billing/services': typeof AuthenticatedCaBillingServicesRoute
  '/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/ca/reports/timesheets': typeof AuthenticatedCaReportsTimesheetsRoute
  '/ca/settings/billing': typeof AuthenticatedCaSettingsBillingRoute
  '/ca/staff/$userId': typeof AuthenticatedCaStaffUserIdRoute
  '/ca/tasks/my-tasks': typeof AuthenticatedCaTasksMyTasksRoute
  '/ca/timesheets/my-timesheet': typeof AuthenticatedCaTimesheetsMyTimesheetRoute
  '/ca/billing/$invoiceId/edit': typeof AuthenticatedCaBillingInvoiceIdEditRoute
  '/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
  '/ca/clients/$clientId/documents': typeof AuthenticatedCaClientsClientIdDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/ca': typeof AuthenticatedCaRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/signup/ca': typeof SignupCaRoute
  '/signup/': typeof SignupIndexRoute
  '/_authenticated/ca/billing': typeof AuthenticatedCaBillingRouteWithChildren
  '/_authenticated/ca/clients': typeof AuthenticatedCaClientsRouteWithChildren
  '/_authenticated/ca/communications': typeof AuthenticatedCaCommunicationsRoute
  '/_authenticated/ca/compliance-calendar': typeof AuthenticatedCaComplianceCalendarRoute
  '/_authenticated/ca/dashboard': typeof AuthenticatedCaDashboardRoute
  '/_authenticated/ca/dsc-vault': typeof AuthenticatedCaDscVaultRoute
  '/_authenticated/ca/reports': typeof AuthenticatedCaReportsRouteWithChildren
  '/_authenticated/ca/settings': typeof AuthenticatedCaSettingsRouteWithChildren
  '/_authenticated/ca/staff': typeof AuthenticatedCaStaffRouteWithChildren
  '/_authenticated/ca/tasks': typeof AuthenticatedCaTasksRouteWithChildren
  '/_authenticated/ca/timesheets': typeof AuthenticatedCaTimesheetsRouteWithChildren
  '/_authenticated/ca/vault': typeof AuthenticatedCaVaultRoute
  '/_authenticated/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/client/requests': typeof AuthenticatedClientRequestsRoute
  '/_authenticated/client/upload': typeof AuthenticatedClientUploadRoute
  '/_authenticated/ca/': typeof AuthenticatedCaIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/ca/billing/$invoiceId': typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  '/_authenticated/ca/billing/new': typeof AuthenticatedCaBillingNewRoute
  '/_authenticated/ca/billing/reports': typeof AuthenticatedCaBillingReportsRoute
  '/_authenticated/ca/billing/services': typeof AuthenticatedCaBillingServicesRoute
  '/_authenticated/ca/clients/$clientId': typeof AuthenticatedCaClientsClientIdRouteWithChildren
  '/_authenticated/ca/reports/timesheets': typeof AuthenticatedCaReportsTimesheetsRoute
  '/_authenticated/ca/settings/billing': typeof AuthenticatedCaSettingsBillingRoute
  '/_authenticated/ca/staff/$userId': typeof AuthenticatedCaStaffUserIdRoute
  '/_authenticated/ca/tasks/my-tasks': typeof AuthenticatedCaTasksMyTasksRoute
  '/_authenticated/ca/timesheets/my-timesheet': typeof AuthenticatedCaTimesheetsMyTimesheetRoute
  '/_authenticated/ca/billing/$invoiceId/edit': typeof AuthenticatedCaBillingInvoiceIdEditRoute
  '/_authenticated/ca/clients/$clientId/compliance': typeof AuthenticatedCaClientsClientIdComplianceRoute
  '/_authenticated/ca/clients/$clientId/documents': typeof AuthenticatedCaClientsClientIdDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/assistant'
    | '/ca'
    | '/client'
    | '/dashboard'
    | '/invoices'
    | '/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/signup/ca'
    | '/signup/'
    | '/ca/billing'
    | '/ca/clients'
    | '/ca/communications'
    | '/ca/compliance-calendar'
    | '/ca/dashboard'
    | '/ca/dsc-vault'
    | '/ca/reports'
    | '/ca/settings'
    | '/ca/staff'
    | '/ca/tasks'
    | '/ca/timesheets'
    | '/ca/vault'
    | '/client/dashboard'
    | '/client/documents'
    | '/client/requests'
    | '/client/upload'
    | '/ca/'
    | '/client/'
    | '/ca/billing/$invoiceId'
    | '/ca/billing/new'
    | '/ca/billing/reports'
    | '/ca/billing/services'
    | '/ca/clients/$clientId'
    | '/ca/reports/timesheets'
    | '/ca/settings/billing'
    | '/ca/staff/$userId'
    | '/ca/tasks/my-tasks'
    | '/ca/timesheets/my-timesheet'
    | '/ca/billing/$invoiceId/edit'
    | '/ca/clients/$clientId/compliance'
    | '/ca/clients/$clientId/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assistant'
    | '/dashboard'
    | '/invoices'
    | '/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/signup/ca'
    | '/signup'
    | '/ca/billing'
    | '/ca/clients'
    | '/ca/communications'
    | '/ca/compliance-calendar'
    | '/ca/dashboard'
    | '/ca/dsc-vault'
    | '/ca/reports'
    | '/ca/settings'
    | '/ca/staff'
    | '/ca/tasks'
    | '/ca/timesheets'
    | '/ca/vault'
    | '/client/dashboard'
    | '/client/documents'
    | '/client/requests'
    | '/client/upload'
    | '/ca'
    | '/client'
    | '/ca/billing/$invoiceId'
    | '/ca/billing/new'
    | '/ca/billing/reports'
    | '/ca/billing/services'
    | '/ca/clients/$clientId'
    | '/ca/reports/timesheets'
    | '/ca/settings/billing'
    | '/ca/staff/$userId'
    | '/ca/tasks/my-tasks'
    | '/ca/timesheets/my-timesheet'
    | '/ca/billing/$invoiceId/edit'
    | '/ca/clients/$clientId/compliance'
    | '/ca/clients/$clientId/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/assistant'
    | '/_authenticated/ca'
    | '/_authenticated/client'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/reminders'
    | '/accept-invite/$token'
    | '/invite/$token'
    | '/signup/ca'
    | '/signup/'
    | '/_authenticated/ca/billing'
    | '/_authenticated/ca/clients'
    | '/_authenticated/ca/communications'
    | '/_authenticated/ca/compliance-calendar'
    | '/_authenticated/ca/dashboard'
    | '/_authenticated/ca/dsc-vault'
    | '/_authenticated/ca/reports'
    | '/_authenticated/ca/settings'
    | '/_authenticated/ca/staff'
    | '/_authenticated/ca/tasks'
    | '/_authenticated/ca/timesheets'
    | '/_authenticated/ca/vault'
    | '/_authenticated/client/dashboard'
    | '/_authenticated/client/documents'
    | '/_authenticated/client/requests'
    | '/_authenticated/client/upload'
    | '/_authenticated/ca/'
    | '/_authenticated/client/'
    | '/_authenticated/ca/billing/$invoiceId'
    | '/_authenticated/ca/billing/new'
    | '/_authenticated/ca/billing/reports'
    | '/_authenticated/ca/billing/services'
    | '/_authenticated/ca/clients/$clientId'
    | '/_authenticated/ca/reports/timesheets'
    | '/_authenticated/ca/settings/billing'
    | '/_authenticated/ca/staff/$userId'
    | '/_authenticated/ca/tasks/my-tasks'
    | '/_authenticated/ca/timesheets/my-timesheet'
    | '/_authenticated/ca/billing/$invoiceId/edit'
    | '/_authenticated/ca/clients/$clientId/compliance'
    | '/_authenticated/ca/clients/$clientId/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRouteWithChildren
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/ca': {
      id: '/signup/ca'
      path: '/ca'
      fullPath: '/signup/ca'
      preLoaderRoute: typeof SignupCaRouteImport
      parentRoute: typeof SignupRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ca': {
      id: '/_authenticated/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof AuthenticatedCaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/ca/': {
      id: '/_authenticated/ca/'
      path: '/'
      fullPath: '/ca/'
      preLoaderRoute: typeof AuthenticatedCaIndexRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/client/upload': {
      id: '/_authenticated/client/upload'
      path: '/upload'
      fullPath: '/client/upload'
      preLoaderRoute: typeof AuthenticatedClientUploadRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/requests': {
      id: '/_authenticated/client/requests'
      path: '/requests'
      fullPath: '/client/requests'
      preLoaderRoute: typeof AuthenticatedClientRequestsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/documents': {
      id: '/_authenticated/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/dashboard': {
      id: '/_authenticated/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/ca/vault': {
      id: '/_authenticated/ca/vault'
      path: '/vault'
      fullPath: '/ca/vault'
      preLoaderRoute: typeof AuthenticatedCaVaultRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/timesheets': {
      id: '/_authenticated/ca/timesheets'
      path: '/timesheets'
      fullPath: '/ca/timesheets'
      preLoaderRoute: typeof AuthenticatedCaTimesheetsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/tasks': {
      id: '/_authenticated/ca/tasks'
      path: '/tasks'
      fullPath: '/ca/tasks'
      preLoaderRoute: typeof AuthenticatedCaTasksRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/staff': {
      id: '/_authenticated/ca/staff'
      path: '/staff'
      fullPath: '/ca/staff'
      preLoaderRoute: typeof AuthenticatedCaStaffRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/settings': {
      id: '/_authenticated/ca/settings'
      path: '/settings'
      fullPath: '/ca/settings'
      preLoaderRoute: typeof AuthenticatedCaSettingsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/reports': {
      id: '/_authenticated/ca/reports'
      path: '/reports'
      fullPath: '/ca/reports'
      preLoaderRoute: typeof AuthenticatedCaReportsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/dsc-vault': {
      id: '/_authenticated/ca/dsc-vault'
      path: '/dsc-vault'
      fullPath: '/ca/dsc-vault'
      preLoaderRoute: typeof AuthenticatedCaDscVaultRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/dashboard': {
      id: '/_authenticated/ca/dashboard'
      path: '/dashboard'
      fullPath: '/ca/dashboard'
      preLoaderRoute: typeof AuthenticatedCaDashboardRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/compliance-calendar': {
      id: '/_authenticated/ca/compliance-calendar'
      path: '/compliance-calendar'
      fullPath: '/ca/compliance-calendar'
      preLoaderRoute: typeof AuthenticatedCaComplianceCalendarRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/communications': {
      id: '/_authenticated/ca/communications'
      path: '/communications'
      fullPath: '/ca/communications'
      preLoaderRoute: typeof AuthenticatedCaCommunicationsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/clients': {
      id: '/_authenticated/ca/clients'
      path: '/clients'
      fullPath: '/ca/clients'
      preLoaderRoute: typeof AuthenticatedCaClientsRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/billing': {
      id: '/_authenticated/ca/billing'
      path: '/billing'
      fullPath: '/ca/billing'
      preLoaderRoute: typeof AuthenticatedCaBillingRouteImport
      parentRoute: typeof AuthenticatedCaRoute
    }
    '/_authenticated/ca/timesheets/my-timesheet': {
      id: '/_authenticated/ca/timesheets/my-timesheet'
      path: '/my-timesheet'
      fullPath: '/ca/timesheets/my-timesheet'
      preLoaderRoute: typeof AuthenticatedCaTimesheetsMyTimesheetRouteImport
      parentRoute: typeof AuthenticatedCaTimesheetsRoute
    }
    '/_authenticated/ca/tasks/my-tasks': {
      id: '/_authenticated/ca/tasks/my-tasks'
      path: '/my-tasks'
      fullPath: '/ca/tasks/my-tasks'
      preLoaderRoute: typeof AuthenticatedCaTasksMyTasksRouteImport
      parentRoute: typeof AuthenticatedCaTasksRoute
    }
    '/_authenticated/ca/staff/$userId': {
      id: '/_authenticated/ca/staff/$userId'
      path: '/$userId'
      fullPath: '/ca/staff/$userId'
      preLoaderRoute: typeof AuthenticatedCaStaffUserIdRouteImport
      parentRoute: typeof AuthenticatedCaStaffRoute
    }
    '/_authenticated/ca/settings/billing': {
      id: '/_authenticated/ca/settings/billing'
      path: '/billing'
      fullPath: '/ca/settings/billing'
      preLoaderRoute: typeof AuthenticatedCaSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedCaSettingsRoute
    }
    '/_authenticated/ca/reports/timesheets': {
      id: '/_authenticated/ca/reports/timesheets'
      path: '/timesheets'
      fullPath: '/ca/reports/timesheets'
      preLoaderRoute: typeof AuthenticatedCaReportsTimesheetsRouteImport
      parentRoute: typeof AuthenticatedCaReportsRoute
    }
    '/_authenticated/ca/clients/$clientId': {
      id: '/_authenticated/ca/clients/$clientId'
      path: '/$clientId'
      fullPath: '/ca/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedCaClientsRoute
    }
    '/_authenticated/ca/billing/services': {
      id: '/_authenticated/ca/billing/services'
      path: '/services'
      fullPath: '/ca/billing/services'
      preLoaderRoute: typeof AuthenticatedCaBillingServicesRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/billing/reports': {
      id: '/_authenticated/ca/billing/reports'
      path: '/reports'
      fullPath: '/ca/billing/reports'
      preLoaderRoute: typeof AuthenticatedCaBillingReportsRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/billing/new': {
      id: '/_authenticated/ca/billing/new'
      path: '/new'
      fullPath: '/ca/billing/new'
      preLoaderRoute: typeof AuthenticatedCaBillingNewRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/billing/$invoiceId': {
      id: '/_authenticated/ca/billing/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/ca/billing/$invoiceId'
      preLoaderRoute: typeof AuthenticatedCaBillingInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedCaBillingRoute
    }
    '/_authenticated/ca/clients/$clientId/documents': {
      id: '/_authenticated/ca/clients/$clientId/documents'
      path: '/documents'
      fullPath: '/ca/clients/$clientId/documents'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/clients/$clientId/compliance': {
      id: '/_authenticated/ca/clients/$clientId/compliance'
      path: '/compliance'
      fullPath: '/ca/clients/$clientId/compliance'
      preLoaderRoute: typeof AuthenticatedCaClientsClientIdComplianceRouteImport
      parentRoute: typeof AuthenticatedCaClientsClientIdRoute
    }
    '/_authenticated/ca/billing/$invoiceId/edit': {
      id: '/_authenticated/ca/billing/$invoiceId/edit'
      path: '/edit'
      fullPath: '/ca/billing/$invoiceId/edit'
      preLoaderRoute: typeof AuthenticatedCaBillingInvoiceIdEditRouteImport
      parentRoute: typeof AuthenticatedCaBillingInvoiceIdRoute
    }
  }
}

interface AuthenticatedCaBillingInvoiceIdRouteChildren {
  AuthenticatedCaBillingInvoiceIdEditRoute: typeof AuthenticatedCaBillingInvoiceIdEditRoute
}

const AuthenticatedCaBillingInvoiceIdRouteChildren: AuthenticatedCaBillingInvoiceIdRouteChildren =
  {
    AuthenticatedCaBillingInvoiceIdEditRoute:
      AuthenticatedCaBillingInvoiceIdEditRoute,
  }

const AuthenticatedCaBillingInvoiceIdRouteWithChildren =
  AuthenticatedCaBillingInvoiceIdRoute._addFileChildren(
    AuthenticatedCaBillingInvoiceIdRouteChildren,
  )

interface AuthenticatedCaBillingRouteChildren {
  AuthenticatedCaBillingInvoiceIdRoute: typeof AuthenticatedCaBillingInvoiceIdRouteWithChildren
  AuthenticatedCaBillingNewRoute: typeof AuthenticatedCaBillingNewRoute
  AuthenticatedCaBillingReportsRoute: typeof AuthenticatedCaBillingReportsRoute
  AuthenticatedCaBillingServicesRoute: typeof AuthenticatedCaBillingServicesRoute
}

const AuthenticatedCaBillingRouteChildren: AuthenticatedCaBillingRouteChildren =
  {
    AuthenticatedCaBillingInvoiceIdRoute:
      AuthenticatedCaBillingInvoiceIdRouteWithChildren,
    AuthenticatedCaBillingNewRoute: AuthenticatedCaBillingNewRoute,
    AuthenticatedCaBillingReportsRoute: AuthenticatedCaBillingReportsRoute,
    AuthenticatedCaBillingServicesRoute: AuthenticatedCaBillingServicesRoute,
  }

const AuthenticatedCaBillingRouteWithChildren =
  AuthenticatedCaBillingRoute._addFileChildren(
    AuthenticatedCaBillingRouteChildren,
  )

interface AuthenticatedCaClientsClientIdRouteChildren {
  AuthenticatedCaClientsClientIdComplianceRoute: typeof AuthenticatedCaClientsClientIdComplianceRoute
  AuthenticatedCaClientsClientIdDocumentsRoute: typeof AuthenticatedCaClientsClientIdDocumentsRoute
}

const AuthenticatedCaClientsClientIdRouteChildren: AuthenticatedCaClientsClientIdRouteChildren =
  {
    AuthenticatedCaClientsClientIdComplianceRoute:
      AuthenticatedCaClientsClientIdComplianceRoute,
    AuthenticatedCaClientsClientIdDocumentsRoute:
      AuthenticatedCaClientsClientIdDocumentsRoute,
  }

const AuthenticatedCaClientsClientIdRouteWithChildren =
  AuthenticatedCaClientsClientIdRoute._addFileChildren(
    AuthenticatedCaClientsClientIdRouteChildren,
  )

interface AuthenticatedCaClientsRouteChildren {
  AuthenticatedCaClientsClientIdRoute: typeof AuthenticatedCaClientsClientIdRouteWithChildren
}

const AuthenticatedCaClientsRouteChildren: AuthenticatedCaClientsRouteChildren =
  {
    AuthenticatedCaClientsClientIdRoute:
      AuthenticatedCaClientsClientIdRouteWithChildren,
  }

const AuthenticatedCaClientsRouteWithChildren =
  AuthenticatedCaClientsRoute._addFileChildren(
    AuthenticatedCaClientsRouteChildren,
  )

interface AuthenticatedCaReportsRouteChildren {
  AuthenticatedCaReportsTimesheetsRoute: typeof AuthenticatedCaReportsTimesheetsRoute
}

const AuthenticatedCaReportsRouteChildren: AuthenticatedCaReportsRouteChildren =
  {
    AuthenticatedCaReportsTimesheetsRoute:
      AuthenticatedCaReportsTimesheetsRoute,
  }

const AuthenticatedCaReportsRouteWithChildren =
  AuthenticatedCaReportsRoute._addFileChildren(
    AuthenticatedCaReportsRouteChildren,
  )

interface AuthenticatedCaSettingsRouteChildren {
  AuthenticatedCaSettingsBillingRoute: typeof AuthenticatedCaSettingsBillingRoute
}

const AuthenticatedCaSettingsRouteChildren: AuthenticatedCaSettingsRouteChildren =
  {
    AuthenticatedCaSettingsBillingRoute: AuthenticatedCaSettingsBillingRoute,
  }

const AuthenticatedCaSettingsRouteWithChildren =
  AuthenticatedCaSettingsRoute._addFileChildren(
    AuthenticatedCaSettingsRouteChildren,
  )

interface AuthenticatedCaStaffRouteChildren {
  AuthenticatedCaStaffUserIdRoute: typeof AuthenticatedCaStaffUserIdRoute
}

const AuthenticatedCaStaffRouteChildren: AuthenticatedCaStaffRouteChildren = {
  AuthenticatedCaStaffUserIdRoute: AuthenticatedCaStaffUserIdRoute,
}

const AuthenticatedCaStaffRouteWithChildren =
  AuthenticatedCaStaffRoute._addFileChildren(AuthenticatedCaStaffRouteChildren)

interface AuthenticatedCaTasksRouteChildren {
  AuthenticatedCaTasksMyTasksRoute: typeof AuthenticatedCaTasksMyTasksRoute
}

const AuthenticatedCaTasksRouteChildren: AuthenticatedCaTasksRouteChildren = {
  AuthenticatedCaTasksMyTasksRoute: AuthenticatedCaTasksMyTasksRoute,
}

const AuthenticatedCaTasksRouteWithChildren =
  AuthenticatedCaTasksRoute._addFileChildren(AuthenticatedCaTasksRouteChildren)

interface AuthenticatedCaTimesheetsRouteChildren {
  AuthenticatedCaTimesheetsMyTimesheetRoute: typeof AuthenticatedCaTimesheetsMyTimesheetRoute
}

const AuthenticatedCaTimesheetsRouteChildren: AuthenticatedCaTimesheetsRouteChildren =
  {
    AuthenticatedCaTimesheetsMyTimesheetRoute:
      AuthenticatedCaTimesheetsMyTimesheetRoute,
  }

const AuthenticatedCaTimesheetsRouteWithChildren =
  AuthenticatedCaTimesheetsRoute._addFileChildren(
    AuthenticatedCaTimesheetsRouteChildren,
  )

interface AuthenticatedCaRouteChildren {
  AuthenticatedCaBillingRoute: typeof AuthenticatedCaBillingRouteWithChildren
  AuthenticatedCaClientsRoute: typeof AuthenticatedCaClientsRouteWithChildren
  AuthenticatedCaCommunicationsRoute: typeof AuthenticatedCaCommunicationsRoute
  AuthenticatedCaComplianceCalendarRoute: typeof AuthenticatedCaComplianceCalendarRoute
  AuthenticatedCaDashboardRoute: typeof AuthenticatedCaDashboardRoute
  AuthenticatedCaDscVaultRoute: typeof AuthenticatedCaDscVaultRoute
  AuthenticatedCaReportsRoute: typeof AuthenticatedCaReportsRouteWithChildren
  AuthenticatedCaSettingsRoute: typeof AuthenticatedCaSettingsRouteWithChildren
  AuthenticatedCaStaffRoute: typeof AuthenticatedCaStaffRouteWithChildren
  AuthenticatedCaTasksRoute: typeof AuthenticatedCaTasksRouteWithChildren
  AuthenticatedCaTimesheetsRoute: typeof AuthenticatedCaTimesheetsRouteWithChildren
  AuthenticatedCaVaultRoute: typeof AuthenticatedCaVaultRoute
  AuthenticatedCaIndexRoute: typeof AuthenticatedCaIndexRoute
}

const AuthenticatedCaRouteChildren: AuthenticatedCaRouteChildren = {
  AuthenticatedCaBillingRoute: AuthenticatedCaBillingRouteWithChildren,
  AuthenticatedCaClientsRoute: AuthenticatedCaClientsRouteWithChildren,
  AuthenticatedCaCommunicationsRoute: AuthenticatedCaCommunicationsRoute,
  AuthenticatedCaComplianceCalendarRoute:
    AuthenticatedCaComplianceCalendarRoute,
  AuthenticatedCaDashboardRoute: AuthenticatedCaDashboardRoute,
  AuthenticatedCaDscVaultRoute: AuthenticatedCaDscVaultRoute,
  AuthenticatedCaReportsRoute: AuthenticatedCaReportsRouteWithChildren,
  AuthenticatedCaSettingsRoute: AuthenticatedCaSettingsRouteWithChildren,
  AuthenticatedCaStaffRoute: AuthenticatedCaStaffRouteWithChildren,
  AuthenticatedCaTasksRoute: AuthenticatedCaTasksRouteWithChildren,
  AuthenticatedCaTimesheetsRoute: AuthenticatedCaTimesheetsRouteWithChildren,
  AuthenticatedCaVaultRoute: AuthenticatedCaVaultRoute,
  AuthenticatedCaIndexRoute: AuthenticatedCaIndexRoute,
}

const AuthenticatedCaRouteWithChildren = AuthenticatedCaRoute._addFileChildren(
  AuthenticatedCaRouteChildren,
)

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientRequestsRoute: typeof AuthenticatedClientRequestsRoute
  AuthenticatedClientUploadRoute: typeof AuthenticatedClientUploadRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
  AuthenticatedClientRequestsRoute: AuthenticatedClientRequestsRoute,
  AuthenticatedClientUploadRoute: AuthenticatedClientUploadRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCaRoute: typeof AuthenticatedCaRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCaRoute: AuthenticatedCaRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SignupRouteChildren {
  SignupCaRoute: typeof SignupCaRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCaRoute: SignupCaRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRouteWithChildren,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
